'''Ophthalmic optical coherence tomography scanner features.'''

def register(registry, prefix_registry):
    registry["35475:感官-眼科光学相干断层扫描仪:3x3以黄斑为中心_FAZ区域似圆度(右)"] = is_between_0_and_1
    registry["35476:感官-眼科光学相干断层扫描仪:3x3以黄斑为中心_FAZ区域似圆度(左)"] =  is_between_0_and_1
    registry["35477:感官-眼科光学相干断层扫描仪:3x3以黄斑为中心_FAZ区域周长(右)(m)"] = _validate_hundred_scale_score
    registry["35478:感官-眼科光学相干断层扫描仪:3x3以黄斑为中心_FAZ区域周长(左)(m)"] = _validate_hundred_scale_score
    registry["35479:感官-眼科光学相干断层扫描仪:3x3以黄斑为中心_FAZ区域轮廓不规则度(右)"] = _validate_hundred_scale_score
    registry["35480:感官-眼科光学相干断层扫描仪:3x3以黄斑为中心_FAZ区域轮廓不规则度(左)"] = _validate_hundred_scale_score
    registry["35481:感官-眼科光学相干断层扫描仪:3x3以黄斑为中心_FAZ区域面积(右)(mm2)"] = _validate_hundred_scale_score
    registry["35482:感官-眼科光学相干断层扫描仪:3x3以黄斑为中心_FAZ区域面积(左)(mm2)"] = _validate_hundred_scale_score
    registry["35483:感官-眼科光学相干断层扫描仪:3x3以黄斑为中心_直径1mm圆内血管密度(右)"] = _validate_hundred_scale_score
    registry["35484:感官-眼科光学相干断层扫描仪:直径2.5mm圆中心血管密度(右)"] = _validate_hundred_scale_score
    registry["35485:感官-眼科光学相干断层扫描仪:3x3以黄斑为中心_直径1mm圆内血管密度(左)"] = _validate_hundred_scale_score
    registry["35486:感官-眼科光学相干断层扫描仪:直径2.5mm圆中心血管密度(左)"] = _validate_hundred_scale_score
    registry["35487:感官-眼科光学相干断层扫描仪:3x3以黄斑为中心_直径1mm圆内骨架密度(右)"] = _validate_hundred_scale_score
    registry["35488:感官-眼科光学相干断层扫描仪:直径2.5mm圆中心骨架密度(右)"] = _validate_hundred_scale_score
    registry["35489:感官-眼科光学相干断层扫描仪:3x3以黄斑为中心_直径2mm圆内血管密度(右)"] = _validate_hundred_scale_score
    registry["35490:感官-眼科光学相干断层扫描仪:3x3以黄斑为中心_直径2mm圆内血管密度(左)"] = _validate_hundred_scale_score
    registry["35491:感官-眼科光学相干断层扫描仪:3x3以黄斑为中心_直径2mm圆内骨架密度(右)"] = _validate_hundred_scale_score
    registry["35492:感官-眼科光学相干断层扫描仪:3x3以黄斑为中心_直径2mm圆内骨架密度(左)"] = _validate_hundred_scale_score
    registry["35493:感官-眼科光学相干断层扫描仪:3x3以黄斑为中心_直径3mm圆中下侧血管密度(右)"] = _validate_hundred_scale_score
    registry["35494:感官-眼科光学相干断层扫描仪:3x3以黄斑为中心_直径3mm圆中下侧血管密度(左)"] = _validate_hundred_scale_score
    registry["35495:感官-眼科光学相干断层扫描仪:3x3以黄斑为中心_直径3mm圆中下侧骨架密度(右)"] = _validate_hundred_scale_score
    registry["35496:感官-眼科光学相干断层扫描仪:3x3以黄斑为中心_直径3mm圆中下侧骨架密度(左)"] = _validate_hundred_scale_score
    registry["35497:感官-眼科光学相干断层扫描仪:3x3以黄斑为中心_直径3mm圆中颞侧血管密度(右)"] = _validate_hundred_scale_score
    registry["35498:感官-眼科光学相干断层扫描仪:直径2.5mm圆中颞侧血管密度(右)"] = _validate_hundred_scale_score
    registry["35499:感官-眼科光学相干断层扫描仪:3x3以黄斑为中心_直径3mm圆中颞侧血管密度(左)"] = _validate_hundred_scale_score
    registry["35500:感官-眼科光学相干断层扫描仪:3x3以黄斑为中心_直径3mm圆中颞侧骨架密度(右)"] = _validate_hundred_scale_score
    registry["35501:感官-眼科光学相干断层扫描仪:3x3以黄斑为中心_直径3mm圆中颞侧骨架密度(左)"] = _validate_hundred_scale_score
    registry["35502:感官-眼科光学相干断层扫描仪:3x3以黄斑为中心_直径3mm圆中鼻侧血管密度(右)"] = _validate_hundred_scale_score
    registry["35503:感官-眼科光学相干断层扫描仪:直径2.5mm圆中鼻侧血管密度(右)"] = _validate_hundred_scale_score
    registry["35504:感官-眼科光学相干断层扫描仪:3x3以黄斑为中心_直径3mm圆中鼻侧血管密度(左)"] = _validate_hundred_scale_score
    registry["35505:感官-眼科光学相干断层扫描仪:3x3以黄斑为中心_直径3mm圆中鼻侧骨架密度(右)"] = _validate_hundred_scale_score
    registry["35506:感官-眼科光学相干断层扫描仪:3x3以黄斑为中心_直径3mm圆中鼻侧骨架密度(左)"] = _validate_hundred_scale_score
    registry["35507:感官-眼科光学相干断层扫描仪:3x3以黄斑为中心_直径3mm圆内血管密度(右)"] = _validate_hundred_scale_score
    registry["35508:感官-眼科光学相干断层扫描仪:3x3以黄斑为中心_直径3mm圆内血管密度(左)"] = _validate_hundred_scale_score
    registry["35509:感官-眼科光学相干断层扫描仪:3x3以黄斑为中心_直径3mm圆内骨架密度(右)"] = _validate_hundred_scale_score
    registry["35510:感官-眼科光学相干断层扫描仪:3x3以黄斑为中心_直径3mm圆内骨架密度(左)"] = _validate_hundred_scale_score
    registry["35511:感官-眼科光学相干断层扫描仪:FAZ区域二阶矩椭圆短轴(mm)(右)(mm)"] = _validate_hundred_scale_score
    registry["35512:感官-眼科光学相干断层扫描仪:FAZ区域二阶矩椭圆短轴(mm)(左)(mm)"] = _validate_hundred_scale_score
    registry["35513:感官-眼科光学相干断层扫描仪:FAZ区域二阶矩椭圆长轴(mm)(右)(mm)"] = _validate_hundred_scale_score
    registry["35514:感官-眼科光学相干断层扫描仪:FAZ区域水平直径(mm)(右)(mm)"] = _validate_hundred_scale_score
    registry["35515:感官-眼科光学相干断层扫描仪:FAZ区域二阶矩椭圆长轴(mm)(左)(mm)"] = _validate_hundred_scale_score
    registry["35516:感官-眼科光学相干断层扫描仪:FAZ区域垂直直径(mm)(右)(mm)"] = _validate_hundred_scale_score
    registry["35517:感官-眼科光学相干断层扫描仪:FAZ区域垂直直径(mm)(左)(mm)"] = _validate_hundred_scale_score
    registry["35518:感官-眼科光学相干断层扫描仪:FAZ区域水平直径(mm)(左)(mm)"] = _validate_hundred_scale_score
    registry["35519:感官-眼科光学相干断层扫描仪:FAZ区域的离心率(右)"] = is_between_0_and_1
    registry["35520:感官-眼科光学相干断层扫描仪:FAZ区域的离心率(左)"] = is_between_0_and_1
    registry["35521:感官-眼科光学相干断层扫描仪:FAZ区域非灌注区(mm2)(右)(mm2)"] = _validate_hundred_scale_score
    registry["35522:感官-眼科光学相干断层扫描仪:FAZ区域非灌注区(mm2)(左)(mm2)"] = _validate_hundred_scale_score
    registry["35523:感官-眼科光学相干断层扫描仪:右眼上侧黄斑中心外层密度(%)"] = _validate_hundred_scale_score
    registry["35524:感官-眼科光学相干断层扫描仪:右眼上侧黄斑中心浅层密度(%)"] = _validate_hundred_scale_score
    registry["35525:感官-眼科光学相干断层扫描仪:右眼上侧黄斑中心深层密度(%)"] = _validate_hundred_scale_score
    registry["35526:感官-眼科光学相干断层扫描仪:右眼上侧黄斑中心脉络膜层密度(%)"] = _validate_hundred_scale_score
    registry["35527:感官-眼科光学相干断层扫描仪:右眼下侧黄斑中心外层密度(%)"] = _validate_hundred_scale_score
    registry["35528:感官-眼科光学相干断层扫描仪:右眼下侧黄斑中心浅层密度(%)"] = _validate_hundred_scale_score
    registry["35529:感官-眼科光学相干断层扫描仪:右眼下侧黄斑中心深层密度(%)"] = _validate_hundred_scale_score
    registry["35530:感官-眼科光学相干断层扫描仪:右眼下侧黄斑中心脉络膜层密度(%)"] = _validate_hundred_scale_score
    registry["35531:感官-眼科光学相干断层扫描仪:右眼中心视盘中心外层密度(%)"] = _validate_hundred_scale_score
    registry["35532:感官-眼科光学相干断层扫描仪:右眼中心黄斑中心外层密度(%)"] = _validate_hundred_scale_score
    registry["35533:感官-眼科光学相干断层扫描仪:右眼中心黄斑中心浅层密度(%)"] = _validate_hundred_scale_score
    registry["35534:感官-眼科光学相干断层扫描仪:右眼中心黄斑中心深层密度(%)"] = _validate_hundred_scale_score
    registry["35535:感官-眼科光学相干断层扫描仪:右眼中心黄斑中心脉络膜层密度(%)"] = _validate_hundred_scale_score
    registry["35536:感官-眼科光学相干断层扫描仪:右眼视盘中心RNFL层厚度环均分6等分颞下侧( μm)"] = _validate_hundred_scale_score
    registry["35537:感官-眼科光学相干断层扫描仪:右眼视盘中心RNFL层厚度环均分12等分下颞侧( μm)"] = _validate_hundred_scale_score
    registry["35538:感官-眼科光学相干断层扫描仪:右眼视盘中心RNFL层厚度环均分36等分31区域( μm)"] = _validate_hundred_scale_score
    registry["35539:感官-眼科光学相干断层扫描仪:右眼视盘中心GCL++层厚度环均分6等分颞下侧( μm)"] = _validate_hundred_scale_score
    registry["35540:感官-眼科光学相干断层扫描仪:右眼视盘中心GCL++层厚度环均分12等分下颞侧( μm)"] = _validate_hundred_scale_score
    registry["35541:感官-眼科光学相干断层扫描仪:右眼视盘中心GCL++层厚度环均分36等分31区域( μm)"] = _validate_hundred_scale_score
    registry["35542:感官-眼科光学相干断层扫描仪:右眼视盘中心GCL++层厚度环均分12等分颞上侧( μm)"] = _validate_hundred_scale_score
    registry["35543:感官-眼科光学相干断层扫描仪:右眼视盘中心GCL++层厚度环均分36等分05区域( μm)"] = _validate_hundred_scale_score
    registry["35544:感官-眼科光学相干断层扫描仪:右眼视盘中心GCL++层厚度环均分12等分颞下侧( μm)"] = _validate_hundred_scale_score
    registry["35545:感官-眼科光学相干断层扫描仪:右眼视盘中心GCL++层厚度环均分36等分34区域( μm)"] = _validate_hundred_scale_score
    registry["35546:感官-眼科光学相干断层扫描仪:右眼视盘中心GCL++层厚度环均分12等分颞侧( μm)"] = _validate_hundred_scale_score
    registry["35547:感官-眼科光学相干断层扫描仪:右眼视盘中心GCL++层厚度环均分36等分01区域( μm)"] = _validate_hundred_scale_score
    registry["35548:感官-眼科光学相干断层扫描仪:右眼视盘中心GCL++层厚度环均分36等分02区域( μm)"] = _validate_hundred_scale_score
    registry["35549:感官-眼科光学相干断层扫描仪:右眼视盘中心GCL++层厚度环均分36等分03区域( μm)"] = _validate_hundred_scale_score
    registry["35550:感官-眼科光学相干断层扫描仪:右眼视盘中心GCL++层厚度环均分36等分06区域( μm)"] = _validate_hundred_scale_score
    registry["35551:感官-眼科光学相干断层扫描仪:右眼视盘中心GCL++层厚度环均分36等分35区域( μm)"] = _validate_hundred_scale_score
    registry["35552:感官-眼科光学相干断层扫描仪:右眼视盘中心GCL++层厚度环均分36等分36区域( μm)"] = _validate_hundred_scale_score
    registry["35553:感官-眼科光学相干断层扫描仪:右眼视盘中心GCL++层厚度环均分4等分颞侧( μm)"] = _validate_hundred_scale_score
    registry["35554:感官-眼科光学相干断层扫描仪:右眼视盘中心GCL++层厚度环均分6等分颞侧( μm)"] = _validate_hundred_scale_score
    registry["35555:感官-眼科光学相干断层扫描仪:右眼视盘中心GCL+层厚度环均分12等分上侧( μm)"] = _validate_hundred_scale_score
    registry["35556:感官-眼科光学相干断层扫描仪:右眼视盘中心GCL+层厚度环均分36等分10区域( μm)"] = _validate_hundred_scale_score
    registry["35557:感官-眼科光学相干断层扫描仪:右眼视盘中心GCL+层厚度环均分12等分上鼻侧( μm)"] = _validate_hundred_scale_score
    registry["35558:感官-眼科光学相干断层扫描仪:右眼视盘中心GCL+层厚度环均分12等分下侧( μm)"] = _validate_hundred_scale_score
    registry["35559:感官-眼科光学相干断层扫描仪:右眼视盘中心GCL+层厚度环均分36等分28区域( μm)"] = _validate_hundred_scale_score
    registry["35560:感官-眼科光学相干断层扫描仪:右眼视盘中心GCL+层厚度环均分12等分下鼻侧( μm)"] = _validate_hundred_scale_score
    registry["35561:感官-眼科光学相干断层扫描仪:右眼视盘中心GCL+层厚度环均分36等分08区域( μm)"] = _validate_hundred_scale_score
    registry["35562:感官-眼科光学相干断层扫描仪:右眼视盘中心GCL+层厚度环均分36等分09区域( μm)"] = _validate_hundred_scale_score
    registry["35563:感官-眼科光学相干断层扫描仪:右眼视盘中心GCL+层厚度环均分36等分12区域( μm)"] = _validate_hundred_scale_score
    registry["35564:感官-眼科光学相干断层扫描仪:右眼视盘中心GCL+层厚度环均分36等分13区域( μm)"] = _validate_hundred_scale_score
    registry["35565:感官-眼科光学相干断层扫描仪:右眼视盘中心GCL+层厚度环均分36等分14区域( μm)"] = _validate_hundred_scale_score
    registry["35566:感官-眼科光学相干断层扫描仪:右眼视盘中心GCL+层厚度环均分36等分23区域( μm)"] = _validate_hundred_scale_score
    registry["35567:感官-眼科光学相干断层扫描仪:右眼视盘中心GCL+层厚度环均分36等分24区域( μm)"] = _validate_hundred_scale_score
    registry["35568:感官-眼科光学相干断层扫描仪:右眼视盘中心GCL+层厚度环均分36等分25区域( μm)"] = _validate_hundred_scale_score
    registry["35569:感官-眼科光学相干断层扫描仪:右眼视盘中心GCL+层厚度环均分36等分26区域( μm)"] = _validate_hundred_scale_score
    registry["35570:感官-眼科光学相干断层扫描仪:右眼视盘中心GCL+层厚度环均分36等分27区域( μm)"] = _validate_hundred_scale_score
    registry["35571:感官-眼科光学相干断层扫描仪:右眼视盘中心GCL+层厚度环均分36等分29区域( μm)"] = _validate_hundred_scale_score
    registry["35572:感官-眼科光学相干断层扫描仪:右眼视盘中心GCL+层厚度环均分36等分30区域( μm)"] = _validate_hundred_scale_score
    registry["35573:感官-眼科光学相干断层扫描仪:右眼视盘中心GCL+层厚度环均分4等分上侧( μm)"] = _validate_hundred_scale_score
    registry["35574:感官-眼科光学相干断层扫描仪:右眼视盘中心GCL+层厚度环均分4等分下侧( μm)"] = _validate_hundred_scale_score
    registry["35575:感官-眼科光学相干断层扫描仪:右眼视盘中心GCL+层厚度环均分6等分鼻上侧( μm)"] = _validate_hundred_scale_score
    registry["35576:感官-眼科光学相干断层扫描仪:右眼视盘中心GCL+层厚度环均分6等分鼻下侧( μm)"] = _validate_hundred_scale_score
    registry["35577:感官-眼科光学相干断层扫描仪:右眼视盘中心RNFL层厚度环均分12等分上颞侧( μm)"] = _validate_hundred_scale_score
    registry["35578:感官-眼科光学相干断层扫描仪:右眼视盘中心RNFL层厚度环均分36等分07区域( μm)"] = _validate_hundred_scale_score
    registry["35579:感官-眼科光学相干断层扫描仪:右眼视盘中心GCL++层厚度环均分12等分上颞侧( μm)"] = _validate_hundred_scale_score
    registry["35580:感官-眼科光学相干断层扫描仪:右眼视盘中心GCL++层厚度环均分36等分07区域( μm)"] = _validate_hundred_scale_score
    registry["35581:感官-眼科光学相干断层扫描仪:右眼视盘中心RNFL层厚度环均分12等分颞上侧( μm)"] = _validate_hundred_scale_score
    registry["35582:感官-眼科光学相干断层扫描仪:右眼视盘中心RNFL层厚度环均分36等分04区域( μm)"] = _validate_hundred_scale_score
    registry["35583:感官-眼科光学相干断层扫描仪:右眼视盘中心RNFL层厚度环均分36等分05区域( μm)"] = _validate_hundred_scale_score
    registry["35584:感官-眼科光学相干断层扫描仪:右眼视盘中心GCL++层厚度环均分36等分04区域( μm)"] = _validate_hundred_scale_score
    registry["35585:感官-眼科光学相干断层扫描仪:右眼视盘中心RNFL层厚度环均分36等分06区域( μm)"] = _validate_hundred_scale_score
    registry["35586:感官-眼科光学相干断层扫描仪:右眼视盘中心RNFL层厚度环均分36等分30区域( μm)"] = _validate_hundred_scale_score
    registry["35587:感官-眼科光学相干断层扫描仪:右眼视盘中心GCL++层厚度环均分36等分30区域( μm)"] = _validate_hundred_scale_score
    registry["35588:感官-眼科光学相干断层扫描仪:右眼视盘中心RNFL层厚度环均分36等分32区域( μm)"] = _validate_hundred_scale_score
    registry["35589:感官-眼科光学相干断层扫描仪:右眼视盘中心GCL++层厚度环均分36等分32区域( μm)"] = _validate_hundred_scale_score
    registry["35590:感官-眼科光学相干断层扫描仪:右眼视盘中心RNFL层厚度环均分36等分33区域( μm)"] = _validate_hundred_scale_score
    registry["35592:感官-眼科光学相干断层扫描仪:右眼视盘中心RNFL层厚度环均分6等分颞上侧( μm)"] = _validate_hundred_scale_score
    registry["35593:感官-眼科光学相干断层扫描仪:右眼视盘中心GCL++层厚度环均分6等分颞上侧( μm)"] = _validate_hundred_scale_score
    registry["35594:感官-眼科光学相干断层扫描仪:右眼视盘中心Retina层厚度环均分6等分颞上侧( μm)"] = _validate_hundred_scale_score
    registry["35595:感官-眼科光学相干断层扫描仪:右眼视盘中心Retina层厚度环均分12等分上颞侧( μm)"] = _validate_hundred_scale_score
    registry["35596:感官-眼科光学相干断层扫描仪:右眼视盘中心Retina层厚度环均分36等分07区域( μm)"] = _validate_hundred_scale_score
    registry["35597:感官-眼科光学相干断层扫描仪:右眼视盘中心Retina层厚度环均分12等分颞上侧( μm)"] = _validate_hundred_scale_score
    registry["35598:感官-眼科光学相干断层扫描仪:右眼视盘中心Retina层厚度环均分36等分05区域( μm)"] = _validate_hundred_scale_score
    registry["35599:感官-眼科光学相干断层扫描仪:右眼视盘中心Retina层厚度环均分12等分颞下侧( μm)"] = _validate_hundred_scale_score
    registry["35600:感官-眼科光学相干断层扫描仪:右眼视盘中心Retina层厚度环均分36等分34区域( μm)"] = _validate_hundred_scale_score
    registry["35601:感官-眼科光学相干断层扫描仪:右眼视盘中心Retina层厚度环均分12等分颞侧( μm)"] = _validate_hundred_scale_score
    registry["35602:感官-眼科光学相干断层扫描仪:右眼视盘中心Retina层厚度环均分36等分01区域( μm)"] = _validate_hundred_scale_score
    registry["35603:感官-眼科光学相干断层扫描仪:右眼视盘中心Retina层厚度环均分36等分02区域( μm)"] = _validate_hundred_scale_score
    registry["35604:感官-眼科光学相干断层扫描仪:右眼视盘中心Retina层厚度环均分36等分03区域( μm)"] = _validate_hundred_scale_score
    registry["35605:感官-眼科光学相干断层扫描仪:右眼视盘中心Retina层厚度环均分36等分04区域( μm)"] = _validate_hundred_scale_score
    registry["35606:感官-眼科光学相干断层扫描仪:右眼视盘中心Retina层厚度环均分36等分06区域( μm)"] = _validate_hundred_scale_score
    registry["35607:感官-眼科光学相干断层扫描仪:右眼视盘中心Retina层厚度环均分36等分32区域( μm)"] = _validate_hundred_scale_score
    registry["35608:感官-眼科光学相干断层扫描仪:右眼视盘中心Retina层厚度环均分36等分33区域( μm)"] = _validate_hundred_scale_score
    registry["35609:感官-眼科光学相干断层扫描仪:右眼视盘中心Retina层厚度环均分36等分35区域( μm)"] = _validate_hundred_scale_score
    registry["35610:感官-眼科光学相干断层扫描仪:右眼视盘中心Retina层厚度环均分36等分36区域( μm)"] = _validate_hundred_scale_score
    registry["35611:感官-眼科光学相干断层扫描仪:右眼视盘中心Retina层厚度环均分4等分颞侧( μm)"] = _validate_hundred_scale_score
    registry["35612:感官-眼科光学相干断层扫描仪:右眼视盘中心Retina层厚度环均分6等分颞侧( μm)"] = _validate_hundred_scale_score
    registry["35613:感官-眼科光学相干断层扫描仪:右眼视盘中心Retina层厚度环均分6等分颞下侧( μm)"] = _validate_hundred_scale_score
    registry["35614:感官-眼科光学相干断层扫描仪:右眼视盘中心Retina层厚度环均分12等分下颞侧( μm)"] = _validate_hundred_scale_score
    registry["35615:感官-眼科光学相干断层扫描仪:右眼视盘中心Retina层厚度环均分36等分30区域( μm)"] = _validate_hundred_scale_score
    registry["35616:感官-眼科光学相干断层扫描仪:右眼视盘中心Retina层厚度环均分36等分31区域( μm)"] = _validate_hundred_scale_score
    registry["35617:感官-眼科光学相干断层扫描仪:右眼颞侧黄斑中心外层密度(%)"] = _validate_hundred_scale_score
    registry["35618:感官-眼科光学相干断层扫描仪:右眼颞侧黄斑中心浅层密度(%)"] = _validate_hundred_scale_score
    registry["35619:感官-眼科光学相干断层扫描仪:右眼颞侧黄斑中心深层密度(%)"] = _validate_hundred_scale_score
    registry["35620:感官-眼科光学相干断层扫描仪:右眼颞侧黄斑中心脉络膜层密度(%)"] = _validate_hundred_scale_score
    registry["35621:感官-眼科光学相干断层扫描仪:右眼黄斑中心GCL++层厚度中心( μm)"] = _validate_hundred_scale_score
    registry["35622:感官-眼科光学相干断层扫描仪:右眼黄斑中心GCL++层厚度内环上侧( μm)"] = _validate_hundred_scale_score
    registry["35623:感官-眼科光学相干断层扫描仪:右眼黄斑中心GCL++层厚度内环下侧( μm)"] = _validate_hundred_scale_score
    registry["35624:感官-眼科光学相干断层扫描仪:右眼黄斑中心GCL++层厚度内环颞侧( μm)"] = _validate_hundred_scale_score
    registry["35625:感官-眼科光学相干断层扫描仪:右眼黄斑中心GCL++层厚度内环鼻侧( μm)"] = _validate_hundred_scale_score
    registry["35626:感官-眼科光学相干断层扫描仪:右眼黄斑中心GCL++层厚度外环上侧( μm)"] = _validate_hundred_scale_score
    registry["35627:感官-眼科光学相干断层扫描仪:右眼黄斑中心GCL++层厚度外环下侧( μm)"] = _validate_hundred_scale_score
    registry["35628:感官-眼科光学相干断层扫描仪:右眼黄斑中心GCL++层厚度外环颞侧( μm)"] = _validate_hundred_scale_score
    registry["35629:感官-眼科光学相干断层扫描仪:右眼黄斑中心GCL++层厚度外环鼻侧( μm)"] = _validate_hundred_scale_score
    registry["35630:感官-眼科光学相干断层扫描仪:右眼黄斑中心GCL++层厚度平均( μm)"] = _validate_hundred_scale_score
    registry["35631:感官-眼科光学相干断层扫描仪:右眼黄斑中心GCL+层厚度中心( μm)"] = _validate_hundred_scale_score
    registry["35632:感官-眼科光学相干断层扫描仪:右眼黄斑中心GCL+层厚度内环上侧( μm)"] = _validate_hundred_scale_score
    registry["35633:感官-眼科光学相干断层扫描仪:右眼黄斑中心GCL+层厚度内环下侧( μm)"] = _validate_hundred_scale_score
    registry["35634:感官-眼科光学相干断层扫描仪:右眼黄斑中心GCL+层厚度内环颞侧( μm)"] = _validate_hundred_scale_score
    registry["35635:感官-眼科光学相干断层扫描仪:右眼黄斑中心GCL+层厚度内环鼻侧( μm)"] = _validate_hundred_scale_score
    registry["35636:感官-眼科光学相干断层扫描仪:右眼黄斑中心GCL+层厚度外环上侧( μm)"] = _validate_hundred_scale_score
    registry["35637:感官-眼科光学相干断层扫描仪:右眼黄斑中心GCL+层厚度外环下侧( μm)"] = _validate_hundred_scale_score
    registry["35638:感官-眼科光学相干断层扫描仪:右眼黄斑中心GCL+层厚度外环颞侧( μm)"] = _validate_hundred_scale_score
    registry["35639:感官-眼科光学相干断层扫描仪:右眼黄斑中心GCL+层厚度外环鼻侧( μm)"] = _validate_hundred_scale_score
    registry["35640:感官-眼科光学相干断层扫描仪:右眼黄斑中心GCL+层厚度平均( μm)"] = _validate_hundred_scale_score
    registry["35641:感官-眼科光学相干断层扫描仪:右眼黄斑中心RNFL层厚度中心( μm)"] = _validate_hundred_scale_score
    registry["35642:感官-眼科光学相干断层扫描仪:右眼黄斑中心RNFL层厚度内环上侧( μm)"] = _validate_hundred_scale_score
    registry["35643:感官-眼科光学相干断层扫描仪:右眼黄斑中心RNFL层厚度内环下侧( μm)"] = _validate_hundred_scale_score
    registry["35644:感官-眼科光学相干断层扫描仪:右眼黄斑中心RNFL层厚度内环颞侧( μm)"] = _validate_hundred_scale_score
    registry["35645:感官-眼科光学相干断层扫描仪:右眼黄斑中心RNFL层厚度内环鼻侧( μm)"] = _validate_hundred_scale_score
    registry["35646:感官-眼科光学相干断层扫描仪:右眼黄斑中心RNFL层厚度外环上侧( μm)"] = _validate_hundred_scale_score
    registry["35647:感官-眼科光学相干断层扫描仪:右眼黄斑中心RNFL层厚度外环下侧( μm)"] = _validate_hundred_scale_score
    registry["35648:感官-眼科光学相干断层扫描仪:右眼黄斑中心RNFL层厚度外环颞侧( μm)"] = _validate_hundred_scale_score
    registry["35649:感官-眼科光学相干断层扫描仪:右眼黄斑中心RNFL层厚度外环鼻侧( μm)"] = _validate_hundred_scale_score
    registry["35650:感官-眼科光学相干断层扫描仪:右眼黄斑中心RNFL层厚度平均( μm)"] = _validate_hundred_scale_score
    registry["35651:感官-眼科光学相干断层扫描仪:右眼黄斑中心Retina层厚度中心( μm)"] = _validate_hundred_scale_score
    registry["35652:感官-眼科光学相干断层扫描仪:右眼黄斑中心Retina层厚度内环上侧( μm)"] = _validate_hundred_scale_score
    registry["35653:感官-眼科光学相干断层扫描仪:右眼黄斑中心Retina层厚度内环下侧( μm)"] = _validate_hundred_scale_score
    registry["35654:感官-眼科光学相干断层扫描仪:右眼黄斑中心Retina层厚度内环颞侧( μm)"] = _validate_hundred_scale_score
    registry["35655:感官-眼科光学相干断层扫描仪:右眼黄斑中心Retina层厚度内环鼻侧( μm)"] = _validate_hundred_scale_score
    registry["35656:感官-眼科光学相干断层扫描仪:右眼黄斑中心Retina层厚度外环上侧( μm)"] = _validate_hundred_scale_score
    registry["35657:感官-眼科光学相干断层扫描仪:右眼黄斑中心Retina层厚度外环下侧( μm)"] = _validate_hundred_scale_score
    registry["35658:感官-眼科光学相干断层扫描仪:右眼黄斑中心Retina层厚度外环颞侧( μm)"] = _validate_hundred_scale_score
    registry["35659:感官-眼科光学相干断层扫描仪:右眼黄斑中心Retina层厚度外环鼻侧( μm)"] = _validate_hundred_scale_score
    registry["35660:感官-眼科光学相干断层扫描仪:右眼黄斑中心Retina层厚度平均( μm)"] = _validate_hundred_scale_score
    registry["35661:感官-眼科光学相干断层扫描仪:右眼鼻侧黄斑中心外层密度(%)"] = _validate_hundred_scale_score
    registry["35662:感官-眼科光学相干断层扫描仪:右眼鼻侧黄斑中心浅层密度(%)"] = _validate_hundred_scale_score
    registry["35663:感官-眼科光学相干断层扫描仪:右眼鼻侧黄斑中心深层密度(%)"] = _validate_hundred_scale_score
    registry["35664:感官-眼科光学相干断层扫描仪:大血管密度(右)"] = _validate_hundred_scale_score
    registry["35665:感官-眼科光学相干断层扫描仪:大血管密度(左)"] = _validate_hundred_scale_score
    registry["35666:感官-眼科光学相干断层扫描仪:大血管骨架密度(右)"] = _validate_hundred_scale_score
    registry["35667:感官-眼科光学相干断层扫描仪:大血管骨架密度(左)"] = _validate_hundred_scale_score
    registry["35668:感官-眼科光学相干断层扫描仪:小血管密度(左)"] = _validate_hundred_scale_score
    registry["35669:感官-眼科光学相干断层扫描仪:小血管骨架密度(左)"] = _validate_hundred_scale_score
    registry["35670:感官-眼科光学相干断层扫描仪:小血管骨架密度(右)"] = _validate_hundred_scale_score
    registry["35671:感官-眼科光学相干断层扫描仪:小血管密度(右)"] = _validate_hundred_scale_score
    registry["35672:感官-眼科光学相干断层扫描仪:左眼上侧黄斑中心外层密度(%)"] = _validate_hundred_scale_score
    registry["35673:感官-眼科光学相干断层扫描仪:左眼上侧黄斑中心浅层密度(%)"] = _validate_hundred_scale_score
    registry["35674:感官-眼科光学相干断层扫描仪:左眼上侧黄斑中心深层密度(%)"] = _validate_hundred_scale_score
    registry["35675:感官-眼科光学相干断层扫描仪:左眼下侧黄斑中心外层密度(%)"] = _validate_hundred_scale_score
    registry["35676:感官-眼科光学相干断层扫描仪:左眼下侧黄斑中心浅层密度(%)"] = _validate_hundred_scale_score
    registry["35677:感官-眼科光学相干断层扫描仪:左眼下侧黄斑中心深层密度(%)"] = _validate_hundred_scale_score
    registry["35678:感官-眼科光学相干断层扫描仪:左眼下侧黄斑中心脉络膜层密度(%)"] = _validate_hundred_scale_score
    registry["35679:感官-眼科光学相干断层扫描仪:左眼中心黄斑中心外层密度(%)"] = _validate_hundred_scale_score
    registry["35680:感官-眼科光学相干断层扫描仪:左眼中心黄斑中心浅层密度(%)"] = _validate_hundred_scale_score
    registry["35681:感官-眼科光学相干断层扫描仪:左眼中心黄斑中心深层密度(%)"] = _validate_hundred_scale_score
    registry["35682:感官-眼科光学相干断层扫描仪:左眼中心黄斑中心脉络膜层密度(%)"] = _validate_hundred_scale_score
    registry["35683:感官-眼科光学相干断层扫描仪:左眼视盘中心RNFL层厚度环均分6等分颞下侧( μm)"] = _validate_hundred_scale_score
    registry["35684:感官-眼科光学相干断层扫描仪:左眼视盘中心RNFL层厚度环均分12等分下颞侧( μm)"] = _validate_hundred_scale_score
    registry["35685:感官-眼科光学相干断层扫描仪:左眼视盘中心RNFL层厚度环均分36等分31区域( μm)"] = _validate_hundred_scale_score
    registry["35686:感官-眼科光学相干断层扫描仪:左眼视盘中心GCL++层厚度环均分6等分颞下侧( μm)"] = _validate_hundred_scale_score
    registry["35687:感官-眼科光学相干断层扫描仪:左眼视盘中心GCL++层厚度环均分12等分下颞侧( μm)"] = _validate_hundred_scale_score
    registry["35688:感官-眼科光学相干断层扫描仪:左眼视盘中心GCL++层厚度环均分36等分31区域( μm)"] = _validate_hundred_scale_score
    registry["35689:感官-眼科光学相干断层扫描仪:左眼视盘中心GCL++层厚度环均分12等分颞上侧( μm)"] = _validate_hundred_scale_score
    registry["35690:感官-眼科光学相干断层扫描仪:左眼视盘中心GCL++层厚度环均分36等分04区域( μm)"] = _validate_hundred_scale_score
    registry["35691:感官-眼科光学相干断层扫描仪:左眼视盘中心GCL++层厚度环均分36等分05区域( μm)"] = _validate_hundred_scale_score
    registry["35692:感官-眼科光学相干断层扫描仪:左眼视盘中心GCL++层厚度环均分12等分颞下侧( μm)"] = _validate_hundred_scale_score
    registry["35693:感官-眼科光学相干断层扫描仪:左眼视盘中心GCL++层厚度环均分36等分34区域( μm)"] = _validate_hundred_scale_score
    registry["35694:感官-眼科光学相干断层扫描仪:左眼视盘中心GCL++层厚度环均分12等分颞侧( μm)"] = _validate_hundred_scale_score
    registry["35695:感官-眼科光学相干断层扫描仪:左眼视盘中心GCL++层厚度环均分36等分01区域( μm)"] = _validate_hundred_scale_score
    registry["35696:感官-眼科光学相干断层扫描仪:左眼视盘中心GCL++层厚度环均分36等分02区域( μm)"] = _validate_hundred_scale_score
    registry["35697:感官-眼科光学相干断层扫描仪:左眼视盘中心GCL++层厚度环均分36等分03区域( μm)"] = _validate_hundred_scale_score
    registry["35698:感官-眼科光学相干断层扫描仪:左眼视盘中心RNFL层厚度环均分12等分上颞侧( μm)"] = _validate_hundred_scale_score
    registry["35699:感官-眼科光学相干断层扫描仪:左眼视盘中心RNFL层厚度环均分36等分07区域( μm)"] = _validate_hundred_scale_score
    registry["35700:感官-眼科光学相干断层扫描仪:左眼视盘中心GCL++层厚度环均分12等分上颞侧( μm)"] = _validate_hundred_scale_score
    registry["35701:感官-眼科光学相干断层扫描仪:左眼视盘中心GCL++层厚度环均分36等分07区域( μm)"] = _validate_hundred_scale_score
    registry["35702:感官-眼科光学相干断层扫描仪:左眼视盘中心GCL++层厚度环均分36等分35区域( μm)"] = _validate_hundred_scale_score
    registry["35703:感官-眼科光学相干断层扫描仪:左眼视盘中心GCL++层厚度环均分36等分36区域( μm)"] = _validate_hundred_scale_score
    registry["35704:感官-眼科光学相干断层扫描仪:左眼视盘中心GCL++层厚度环均分4等分颞侧( μm)"] = _validate_hundred_scale_score
    registry["35705:感官-眼科光学相干断层扫描仪:左眼视盘中心GCL++层厚度环均分6等分颞侧( μm)"] = _validate_hundred_scale_score
    registry["35706:感官-眼科光学相干断层扫描仪:左眼视盘中心GCL+层厚度环均分12等分上侧( μm)"] = _validate_hundred_scale_score
    registry["35707:感官-眼科光学相干断层扫描仪:左眼视盘中心GCL+层厚度环均分36等分10区域( μm)"] = _validate_hundred_scale_score
    registry["35708:感官-眼科光学相干断层扫描仪:左眼视盘中心GCL+层厚度环均分12等分上鼻侧( μm)"] = _validate_hundred_scale_score
    registry["35709:感官-眼科光学相干断层扫描仪:左眼视盘中心GCL+层厚度环均分12等分下侧( μm)"] = _validate_hundred_scale_score
    registry["35710:感官-眼科光学相干断层扫描仪:左眼视盘中心GCL+层厚度环均分36等分28区域( μm)"] = _validate_hundred_scale_score
    registry["35711:感官-眼科光学相干断层扫描仪:左眼视盘中心GCL+层厚度环均分12等分下鼻侧( μm)"] = _validate_hundred_scale_score
    registry["35712:感官-眼科光学相干断层扫描仪:左眼视盘中心GCL+层厚度环均分36等分08区域( μm)"] = _validate_hundred_scale_score
    registry["35713:感官-眼科光学相干断层扫描仪:左眼视盘中心GCL+层厚度环均分36等分09区域( μm)"] = _validate_hundred_scale_score
    registry["35714:感官-眼科光学相干断层扫描仪:左眼视盘中心GCL+层厚度环均分36等分12区域( μm)"] = _validate_hundred_scale_score
    registry["35715:感官-眼科光学相干断层扫描仪:左眼视盘中心GCL+层厚度环均分36等分13区域( μm)"] = _validate_hundred_scale_score
    registry["35716:感官-眼科光学相干断层扫描仪:左眼视盘中心GCL+层厚度环均分36等分14区域( μm)"] = _validate_hundred_scale_score
    registry["35717:感官-眼科光学相干断层扫描仪:左眼视盘中心GCL+层厚度环均分36等分24区域( μm)"] = _validate_hundred_scale_score
    registry["35718:感官-眼科光学相干断层扫描仪:左眼视盘中心GCL+层厚度环均分36等分25区域( μm)"] = _validate_hundred_scale_score
    registry["35719:感官-眼科光学相干断层扫描仪:左眼视盘中心GCL+层厚度环均分36等分26区域( μm)"] = _validate_hundred_scale_score
    registry["35720:感官-眼科光学相干断层扫描仪:左眼视盘中心GCL+层厚度环均分36等分27区域( μm)"] = _validate_hundred_scale_score
    registry["35721:感官-眼科光学相干断层扫描仪:左眼视盘中心GCL+层厚度环均分36等分29区域( μm)"] = _validate_hundred_scale_score
    registry["35722:感官-眼科光学相干断层扫描仪:左眼视盘中心GCL+层厚度环均分36等分30区域( μm)"] = _validate_hundred_scale_score
    registry["35723:感官-眼科光学相干断层扫描仪:左眼视盘中心GCL+层厚度环均分4等分上侧( μm)"] = _validate_hundred_scale_score
    registry["35724:感官-眼科光学相干断层扫描仪:左眼视盘中心GCL+层厚度环均分4等分下侧( μm)"] = _validate_hundred_scale_score
    registry["35725:感官-眼科光学相干断层扫描仪:左眼视盘中心GCL+层厚度环均分6等分颞上侧( μm)"] = _validate_hundred_scale_score
    registry["35726:感官-眼科光学相干断层扫描仪:左眼视盘中心GCL+层厚度环均分12等分上颞侧( μm)"] = _validate_hundred_scale_score
    registry["35727:感官-眼科光学相干断层扫描仪:左眼视盘中心GCL+层厚度环均分6等分鼻上侧( μm)"] = _validate_hundred_scale_score
    registry["35728:感官-眼科光学相干断层扫描仪:左眼视盘中心GCL+层厚度环均分6等分鼻下侧( μm)"] = _validate_hundred_scale_score
    registry["35729:感官-眼科光学相干断层扫描仪:左眼视盘中心RNFL层厚度环均分36等分06区域( μm)"] = _validate_hundred_scale_score
    registry["35730:感官-眼科光学相干断层扫描仪:左眼视盘中心GCL++层厚度环均分36等分06区域( μm)"] = _validate_hundred_scale_score
    registry["35731:感官-眼科光学相干断层扫描仪:左眼视盘中心RNFL层厚度环均分36等分30区域( μm)"] = _validate_hundred_scale_score
    registry["35732:感官-眼科光学相干断层扫描仪:左眼视盘中心GCL++层厚度环均分36等分30区域( μm)"] = _validate_hundred_scale_score
    registry["35733:感官-眼科光学相干断层扫描仪:左眼视盘中心RNFL层厚度环均分6等分颞上侧( μm)"] = _validate_hundred_scale_score
    registry["35734:感官-眼科光学相干断层扫描仪:左眼视盘中心GCL++层厚度环均分6等分颞上侧( μm)"] = _validate_hundred_scale_score
    registry["35735:感官-眼科光学相干断层扫描仪:左眼视盘中心Retina层厚度环均分12等分上颞侧( μm)"] = _validate_hundred_scale_score
    registry["35736:感官-眼科光学相干断层扫描仪:左眼视盘中心Retina层厚度环均分36等分07区域( μm)"] = _validate_hundred_scale_score
    registry["35737:感官-眼科光学相干断层扫描仪:左眼视盘中心Retina层厚度环均分12等分颞上侧( μm)"] = _validate_hundred_scale_score
    registry["35738:感官-眼科光学相干断层扫描仪:左眼视盘中心Retina层厚度环均分36等分04区域( μm)"] = _validate_hundred_scale_score
    registry["35739:感官-眼科光学相干断层扫描仪:左眼视盘中心Retina层厚度环均分12等分颞下侧( μm)"] = _validate_hundred_scale_score
    registry["35740:感官-眼科光学相干断层扫描仪:左眼视盘中心Retina层厚度环均分36等分34区域( μm)"] = _validate_hundred_scale_score
    registry["35741:感官-眼科光学相干断层扫描仪:左眼视盘中心Retina层厚度环均分12等分颞侧( μm)"] = _validate_hundred_scale_score
    registry["35742:感官-眼科光学相干断层扫描仪:左眼视盘中心Retina层厚度环均分36等分01区域( μm)"] = _validate_hundred_scale_score
    registry["35743:感官-眼科光学相干断层扫描仪:左眼视盘中心Retina层厚度环均分36等分02区域( μm)"] = _validate_hundred_scale_score
    registry["35744:感官-眼科光学相干断层扫描仪:左眼视盘中心Retina层厚度环均分36等分03区域( μm)"] = _validate_hundred_scale_score
    registry["35745:感官-眼科光学相干断层扫描仪:左眼视盘中心Retina层厚度环均分36等分05区域( μm)"] = _validate_hundred_scale_score
    registry["35746:感官-眼科光学相干断层扫描仪:左眼视盘中心Retina层厚度环均分36等分06区域( μm)"] = _validate_hundred_scale_score
    registry["35747:感官-眼科光学相干断层扫描仪:左眼视盘中心Retina层厚度环均分36等分32区域( μm)"] = _validate_hundred_scale_score
    registry["35748:感官-眼科光学相干断层扫描仪:左眼视盘中心Retina层厚度环均分36等分33区域( μm)"] = _validate_hundred_scale_score
    registry["35749:感官-眼科光学相干断层扫描仪:左眼视盘中心Retina层厚度环均分36等分35区域( μm)"] = _validate_hundred_scale_score
    registry["35750:感官-眼科光学相干断层扫描仪:左眼视盘中心Retina层厚度环均分36等分36区域( μm)"] = _validate_hundred_scale_score
    registry["35751:感官-眼科光学相干断层扫描仪:左眼视盘中心Retina层厚度环均分4等分颞侧( μm)"] = _validate_hundred_scale_score
    registry["35752:感官-眼科光学相干断层扫描仪:左眼视盘中心Retina层厚度环均分6等分颞侧( μm)"] = _validate_hundred_scale_score
    registry["35753:感官-眼科光学相干断层扫描仪:左眼视盘中心Retina层厚度环均分6等分颞上侧( μm)"] = _validate_hundred_scale_score
    registry["35754:感官-眼科光学相干断层扫描仪:左眼视盘中心Retina层厚度环均分6等分颞下侧( μm)"] = _validate_hundred_scale_score
    registry["35755:感官-眼科光学相干断层扫描仪:左眼视盘中心Retina层厚度环均分12等分下颞侧( μm)"] = _validate_hundred_scale_score
    registry["35756:感官-眼科光学相干断层扫描仪:左眼视盘中心Retina层厚度环均分36等分30区域( μm)"] = _validate_hundred_scale_score
    registry["35757:感官-眼科光学相干断层扫描仪:左眼视盘中心Retina层厚度环均分36等分31区域( μm)"] = _validate_hundred_scale_score
    registry["35758:感官-眼科光学相干断层扫描仪:左眼颞侧黄斑中心外层密度(%)"] = _validate_hundred_scale_score
    registry["35759:感官-眼科光学相干断层扫描仪:左眼颞侧黄斑中心浅层密度(%)"] = _validate_hundred_scale_score
    registry["35760:感官-眼科光学相干断层扫描仪:左眼颞侧黄斑中心深层密度(%)"] = _validate_hundred_scale_score
    registry["35761:感官-眼科光学相干断层扫描仪:左眼颞侧黄斑中心脉络膜层密度(%)"] = _validate_hundred_scale_score
    registry["35762:感官-眼科光学相干断层扫描仪:左眼黄斑中心GCL++层厚度中心( μm)"] = _validate_hundred_scale_score
    registry["35763:感官-眼科光学相干断层扫描仪:左眼黄斑中心GCL++层厚度内环上侧( μm)"] = _validate_hundred_scale_score
    registry["35764:感官-眼科光学相干断层扫描仪:左眼黄斑中心GCL++层厚度内环下侧( μm)"] = _validate_hundred_scale_score
    registry["35765:感官-眼科光学相干断层扫描仪:左眼黄斑中心GCL++层厚度内环颞侧( μm)"] = _validate_hundred_scale_score
    registry["35766:感官-眼科光学相干断层扫描仪:左眼黄斑中心GCL++层厚度内环鼻侧( μm)"] = _validate_hundred_scale_score
    registry["35767:感官-眼科光学相干断层扫描仪:左眼黄斑中心GCL++层厚度外环上侧( μm)"] = _validate_hundred_scale_score
    registry["35768:感官-眼科光学相干断层扫描仪:左眼黄斑中心GCL++层厚度外环下侧( μm)"] = _validate_hundred_scale_score
    registry["35769:感官-眼科光学相干断层扫描仪:左眼黄斑中心GCL++层厚度外环颞侧( μm)"] = _validate_hundred_scale_score
    registry["35770:感官-眼科光学相干断层扫描仪:左眼黄斑中心GCL++层厚度外环鼻侧( μm)"] = _validate_hundred_scale_score
    registry["35771:感官-眼科光学相干断层扫描仪:左眼黄斑中心GCL++层厚度平均( μm)"] = _validate_hundred_scale_score
    registry["35772:感官-眼科光学相干断层扫描仪:左眼黄斑中心GCL+层厚度中心( μm)"] = _validate_hundred_scale_score
    registry["35773:感官-眼科光学相干断层扫描仪:左眼黄斑中心GCL+层厚度内环上侧( μm)"] = _validate_hundred_scale_score
    registry["35774:感官-眼科光学相干断层扫描仪:左眼黄斑中心GCL+层厚度内环下侧( μm)"] = _validate_hundred_scale_score
    registry["35775:感官-眼科光学相干断层扫描仪:左眼黄斑中心GCL+层厚度内环颞侧( μm)"] = _validate_hundred_scale_score
    registry["35776:感官-眼科光学相干断层扫描仪:左眼黄斑中心GCL+层厚度内环鼻侧( μm)"] = _validate_hundred_scale_score
    registry["35777:感官-眼科光学相干断层扫描仪:左眼黄斑中心GCL+层厚度外环上侧( μm)"] = _validate_hundred_scale_score
    registry["35778:感官-眼科光学相干断层扫描仪:左眼黄斑中心GCL+层厚度外环下侧( μm)"] = _validate_hundred_scale_score
    registry["35779:感官-眼科光学相干断层扫描仪:左眼黄斑中心GCL+层厚度外环颞侧( μm)"] = _validate_hundred_scale_score
    registry["35780:感官-眼科光学相干断层扫描仪:左眼黄斑中心GCL+层厚度外环鼻侧( μm)"] = _validate_hundred_scale_score
    registry["35781:感官-眼科光学相干断层扫描仪:左眼黄斑中心GCL+层厚度平均( μm)"] = _validate_hundred_scale_score
    registry["35782:感官-眼科光学相干断层扫描仪:左眼黄斑中心RNFL层厚度中心( μm)"] = _validate_hundred_scale_score
    registry["35783:感官-眼科光学相干断层扫描仪:左眼黄斑中心RNFL层厚度内环上侧( μm)"] = _validate_hundred_scale_score
    registry["35784:感官-眼科光学相干断层扫描仪:左眼黄斑中心RNFL层厚度内环下侧( μm)"] = _validate_hundred_scale_score
    registry["35785:感官-眼科光学相干断层扫描仪:左眼黄斑中心RNFL层厚度内环颞侧( μm)"] = _validate_hundred_scale_score
    registry["35786:感官-眼科光学相干断层扫描仪:左眼黄斑中心RNFL层厚度内环鼻侧( μm)"] = _validate_hundred_scale_score
    registry["35787:感官-眼科光学相干断层扫描仪:左眼黄斑中心RNFL层厚度外环上侧( μm)"] = _validate_hundred_scale_score
    registry["35788:感官-眼科光学相干断层扫描仪:左眼黄斑中心RNFL层厚度外环下侧( μm)"] = _validate_hundred_scale_score
    registry["35789:感官-眼科光学相干断层扫描仪:左眼黄斑中心RNFL层厚度外环颞侧( μm)"] = _validate_hundred_scale_score
    registry["35790:感官-眼科光学相干断层扫描仪:左眼黄斑中心RNFL层厚度外环鼻侧( μm)"] = _validate_hundred_scale_score
    registry["35791:感官-眼科光学相干断层扫描仪:左眼黄斑中心RNFL层厚度平均( μm)"] = _validate_hundred_scale_score
    registry["35792:感官-眼科光学相干断层扫描仪:左眼黄斑中心Retina层厚度中心( μm)"] = _validate_hundred_scale_score
    registry["35793:感官-眼科光学相干断层扫描仪:左眼黄斑中心Retina层厚度内环上侧( μm)"] = _validate_hundred_scale_score
    registry["35794:感官-眼科光学相干断层扫描仪:左眼黄斑中心Retina层厚度内环下侧( μm)"] = _validate_hundred_scale_score
    registry["35795:感官-眼科光学相干断层扫描仪:左眼黄斑中心Retina层厚度内环颞侧( μm)"] = _validate_hundred_scale_score
    registry["35796:感官-眼科光学相干断层扫描仪:左眼黄斑中心Retina层厚度内环鼻侧( μm)"] = _validate_hundred_scale_score
    registry["35797:感官-眼科光学相干断层扫描仪:左眼黄斑中心Retina层厚度外环上侧( μm)"] = _validate_hundred_scale_score
    registry["35798:感官-眼科光学相干断层扫描仪:左眼黄斑中心Retina层厚度外环下侧( μm)"] = _validate_hundred_scale_score
    registry["35799:感官-眼科光学相干断层扫描仪:左眼黄斑中心Retina层厚度外环颞侧( μm)"] = _validate_hundred_scale_score
    registry["35800:感官-眼科光学相干断层扫描仪:左眼黄斑中心Retina层厚度外环鼻侧( μm)"] = _validate_hundred_scale_score
    registry["35801:感官-眼科光学相干断层扫描仪:左眼黄斑中心Retina层厚度平均( μm)"] = _validate_hundred_scale_score
    registry["35802:感官-眼科光学相干断层扫描仪:左眼鼻侧视盘中心脉络膜层密度(%)"] = _validate_hundred_scale_score
    registry["35803:感官-眼科光学相干断层扫描仪:左眼鼻侧黄斑中心外层密度(%)"] = _validate_hundred_scale_score
    registry["35804:感官-眼科光学相干断层扫描仪:左眼鼻侧黄斑中心浅层密度(%)"] = _validate_hundred_scale_score
    registry["35805:感官-眼科光学相干断层扫描仪:左眼鼻侧黄斑中心深层密度(%)"] = _validate_hundred_scale_score
    registry["35806:感官-眼科光学相干断层扫描仪:左眼鼻侧黄斑中心脉络膜层密度(%)"] = _validate_hundred_scale_score
    registry["35807:感官-眼科光学相干断层扫描仪:直径2.5mm圆中上侧血管密度(右)"] =_validate_hundred_scale_score
    registry["35808:感官-眼科光学相干断层扫描仪:3x3以黄斑为中心_直径3mm圆中上侧血管密度(右)"] =_validate_hundred_scale_score
    registry["35809:感官-眼科光学相干断层扫描仪:直径2.5mm圆中上侧血管密度(左)"] =_validate_hundred_scale_score
    registry["35810:感官-眼科光学相干断层扫描仪:3x3以黄斑为中心_直径3mm圆中上侧血管密度(左)"] =_validate_hundred_scale_score
    registry["35811:感官-眼科光学相干断层扫描仪:直径2.5mm圆中上侧骨架密度(右)"] =_validate_hundred_scale_score
    registry["35812:感官-眼科光学相干断层扫描仪:3x3以黄斑为中心_直径3mm圆中上侧骨架密度(右)"] =_validate_hundred_scale_score
    registry["35813:感官-眼科光学相干断层扫描仪:直径2.5mm圆中上侧骨架密度(左)"] =_validate_hundred_scale_score
    registry["35814:感官-眼科光学相干断层扫描仪:3x3以黄斑为中心_直径3mm圆中上侧骨架密度(左)"] =_validate_hundred_scale_score
    registry["35815:感官-眼科光学相干断层扫描仪:直径2.5mm圆中下侧血管密度(右)"] =_validate_hundred_scale_score
    registry["35816:感官-眼科光学相干断层扫描仪:直径2.5mm圆中下侧血管密度(左)"] =_validate_hundred_scale_score
    registry["35817:感官-眼科光学相干断层扫描仪:直径2.5mm圆中下侧骨架密度(右)"] =_validate_hundred_scale_score
    registry["35818:感官-眼科光学相干断层扫描仪:直径2.5mm圆中下侧骨架密度(左)"] =_validate_hundred_scale_score
    registry["35819:感官-眼科光学相干断层扫描仪:直径2.5mm圆中心骨架密度(左)"] =_validate_hundred_scale_score
    registry["35820:感官-眼科光学相干断层扫描仪:3x3以黄斑为中心_直径1mm圆内骨架密度(左)"] =_validate_hundred_scale_score
    registry["35821:感官-眼科光学相干断层扫描仪:直径2.5mm圆中颞侧血管密度(左)"] =_validate_hundred_scale_score
    registry["35822:感官-眼科光学相干断层扫描仪:直径2.5mm圆中颞侧骨架密度(右)"] =_validate_hundred_scale_score
    registry["35823:感官-眼科光学相干断层扫描仪:直径2.5mm圆中颞侧骨架密度(左)"] =_validate_hundred_scale_score
    registry["35824:感官-眼科光学相干断层扫描仪:直径2.5mm圆中鼻侧血管密度(左)"] =_validate_hundred_scale_score
    registry["35825:感官-眼科光学相干断层扫描仪:直径2.5mm圆中鼻侧骨架密度(右)"] =_validate_hundred_scale_score
    registry["35826:感官-眼科光学相干断层扫描仪:直径2.5mm圆中鼻侧骨架密度(左)"] =_validate_hundred_scale_score
    registry["35827:感官-眼科光学相干断层扫描仪:血管周长指数(右)"] =_validate_hundred_scale_score
    registry["35828:感官-眼科光学相干断层扫描仪:血管周长指数(左)"] =_validate_hundred_scale_score
    registry["35829:感官-眼科光学相干断层扫描仪:血管复杂度(右)"] =_validate_hundred_scale_score
    registry["35830:感官-眼科光学相干断层扫描仪:血管复杂度(左)"] =_validate_hundred_scale_score
    registry["35831:感官-眼科光学相干断层扫描仪:血管密度(右)"] =_validate_hundred_scale_score
    registry["35832:感官-眼科光学相干断层扫描仪:血管密度(左)"] =_validate_hundred_scale_score
    registry["35833:感官-眼科光学相干断层扫描仪:血管直径指数(右)"] =_validate_hundred_scale_score
    registry["35834:感官-眼科光学相干断层扫描仪:血管直径指数(左)"] =_validate_hundred_scale_score
    registry["35835:感官-眼科光学相干断层扫描仪:血管骨架分形维数(右)"] =_validate_hundred_scale_score
    registry["35836:感官-眼科光学相干断层扫描仪:血管骨架分形维数(左)"] =_validate_hundred_scale_score
    registry["35837:感官-眼科光学相干断层扫描仪:血管骨架密度(右)"] =_validate_hundred_scale_score
    registry["35838:感官-眼科光学相干断层扫描仪:血管骨架密度(左)"] =_validate_hundred_scale_score
    registry["35891:感官-眼科光学相干断层扫描仪:右眼视盘中心GCL+层厚度环均分12等分鼻上侧( μm)"] =_validate_hundred_scale_score
    registry["35892:感官-眼科光学相干断层扫描仪:右眼视盘中心GCL+层厚度环均分12等分鼻下侧( μm)"] =_validate_hundred_scale_score
    registry["35893:感官-眼科光学相干断层扫描仪:右眼视盘中心GCL+层厚度环均分36等分11区域( μm)"] =_validate_hundred_scale_score
    registry["35894:感官-眼科光学相干断层扫描仪:右眼视盘中心GCL+层厚度环均分36等分15区域( μm)"] =_validate_hundred_scale_score
    registry["35895:感官-眼科光学相干断层扫描仪:右眼视盘中心GCL+层厚度环均分36等分16区域( μm)"] =_validate_hundred_scale_score
    registry["35896:感官-眼科光学相干断层扫描仪:右眼视盘中心GCL+层厚度环均分36等分22区域( μm)"] =_validate_hundred_scale_score
    registry["35897:感官-眼科光学相干断层扫描仪:右眼视盘中心GCL+层厚度环均分4等分鼻侧( μm)"] =_validate_hundred_scale_score
    registry["35898:感官-眼科光学相干断层扫描仪:右眼视盘中心GCL+层厚度环均分6等分鼻侧( μm)"] =_validate_hundred_scale_score
    registry["35899:感官-眼科光学相干断层扫描仪:右眼视盘中心GCL+层厚度环均分6等分颞上侧( μm)"] =_validate_hundred_scale_score
    registry["35900:感官-眼科光学相干断层扫描仪:右眼视盘中心GCL+层厚度环均分12等分上颞侧( μm)"] =_validate_hundred_scale_score
    registry["35901:感官-眼科光学相干断层扫描仪:右眼鼻侧黄斑中心脉络膜层密度(%)"] = _validate_hundred_scale_score
    registry["35902:感官-眼科光学相干断层扫描仪:左眼上侧黄斑中心脉络膜层密度(%)"] = _validate_hundred_scale_score
    registry["35903:感官-眼科光学相干断层扫描仪:左眼视盘中心GCL+层厚度平均( μm)"] =_validate_hundred_scale_score
    registry["35904:感官-眼科光学相干断层扫描仪:左眼视盘中心GCL+层厚度环均分12等分鼻上侧( μm)"] =_validate_hundred_scale_score
    registry["35905:感官-眼科光学相干断层扫描仪:左眼视盘中心GCL+层厚度环均分12等分鼻下侧( μm)"] =_validate_hundred_scale_score
    registry["35906:感官-眼科光学相干断层扫描仪:左眼视盘中心GCL+层厚度环均分12等分鼻侧( μm)"] =_validate_hundred_scale_score
    registry["35907:感官-眼科光学相干断层扫描仪:左眼视盘中心GCL+层厚度环均分36等分11区域( μm)"] =_validate_hundred_scale_score
    registry["35908:感官-眼科光学相干断层扫描仪:左眼视盘中心GCL+层厚度环均分36等分15区域( μm)"] =_validate_hundred_scale_score
    registry["35909:感官-眼科光学相干断层扫描仪:左眼视盘中心GCL+层厚度环均分36等分16区域( μm)"] =_validate_hundred_scale_score
    registry["35910:感官-眼科光学相干断层扫描仪:左眼视盘中心GCL+层厚度环均分36等分17区域( μm)"] =_validate_hundred_scale_score
    registry["35911:感官-眼科光学相干断层扫描仪:左眼视盘中心GCL+层厚度环均分36等分18区域( μm)"] =_validate_hundred_scale_score
    registry["35912:感官-眼科光学相干断层扫描仪:左眼视盘中心GCL+层厚度环均分36等分19区域( μm)"] =_validate_hundred_scale_score
    registry["35913:感官-眼科光学相干断层扫描仪:左眼视盘中心GCL+层厚度环均分36等分20区域( μm)"] =_validate_hundred_scale_score
    registry["35914:感官-眼科光学相干断层扫描仪:左眼视盘中心GCL+层厚度环均分36等分21区域( μm)"] =_validate_hundred_scale_score
    registry["35915:感官-眼科光学相干断层扫描仪:左眼视盘中心GCL+层厚度环均分36等分22区域( μm)"] =_validate_hundred_scale_score
    registry["35916:感官-眼科光学相干断层扫描仪:左眼视盘中心GCL+层厚度环均分36等分23区域( μm)"] =_validate_hundred_scale_score
    registry["35917:感官-眼科光学相干断层扫描仪:左眼视盘中心GCL+层厚度环均分4等分鼻侧( μm)"] =_validate_hundred_scale_score
    registry["35918:感官-眼科光学相干断层扫描仪:左眼视盘中心GCL+层厚度环均分6等分鼻侧( μm)"] =_validate_hundred_scale_score
    registry["35954:感官-眼科光学相干断层扫描仪:右眼上侧视盘中心外层密度(%)"] = _validate_hundred_scale_score
    registry["35955:感官-眼科光学相干断层扫描仪:右眼上侧视盘中心浅层密度(%)"] = _validate_hundred_scale_score
    registry["35956:感官-眼科光学相干断层扫描仪:右眼上侧视盘中心深层密度(%)"] = _validate_hundred_scale_score
    registry["35957:感官-眼科光学相干断层扫描仪:右眼上侧视盘中心脉络膜层密度(%)"] = _validate_hundred_scale_score
    registry["35958:感官-眼科光学相干断层扫描仪:右眼下侧视盘中心外层密度(%)"] = _validate_hundred_scale_score
    registry["35959:感官-眼科光学相干断层扫描仪:右眼下侧视盘中心浅层密度(%)"] = _validate_hundred_scale_score
    registry["35960:感官-眼科光学相干断层扫描仪:右眼下侧视盘中心深层密度(%)"] = _validate_hundred_scale_score
    registry["35961:感官-眼科光学相干断层扫描仪:右眼下侧视盘中心脉络膜层密度(%)"] = _validate_hundred_scale_score
    registry["35962:感官-眼科光学相干断层扫描仪:右眼中心视盘中心浅层密度(%)"] = _validate_hundred_scale_score
    registry["35963:感官-眼科光学相干断层扫描仪:右眼中心视盘中心深层密度(%)"] = _validate_hundred_scale_score
    registry["35964:感官-眼科光学相干断层扫描仪:右眼中心视盘中心脉络膜层密度(%)"] = _validate_hundred_scale_score
    registry["35965:感官-眼科光学相干断层扫描仪:右眼盘沿体积(mm3)"] =_validate_hundred_scale_score
    registry["35966:感官-眼科光学相干断层扫描仪:右眼盘沿面积(mm2)"] =_validate_hundred_scale_score
    registry["35967:感官-眼科光学相干断层扫描仪:右眼视杯与视盘面积比率"] =_validate_hundred_scale_score
    registry["35968:感官-眼科光学相干断层扫描仪:右眼视杯与视盘面积比率的平方根"] =_validate_hundred_scale_score
    registry["35969:感官-眼科光学相干断层扫描仪:右眼视杯与视盘纵向直径比率"] =_validate_hundred_scale_score
    registry["35970:感官-眼科光学相干断层扫描仪:右眼视杯体积(mm3)"] =_validate_hundred_scale_score
    registry["35971:感官-眼科光学相干断层扫描仪:右眼视杯面积(mm2)"] =_validate_hundred_scale_score
    registry["35972:感官-眼科光学相干断层扫描仪:右眼视盘中心Choroid层厚度平均( μm)"] =_validate_hundred_scale_score
    registry["35973:感官-眼科光学相干断层扫描仪:右眼视盘中心Choroid层厚度环均分12等分颞上侧( μm)"] =_validate_hundred_scale_score
    registry["35974:感官-眼科光学相干断层扫描仪:右眼视盘中心Choroid层厚度环均分36等分04区域( μm)"] =_validate_hundred_scale_score
    registry["35975:感官-眼科光学相干断层扫描仪:右眼视盘中心Choroid层厚度环均分36等分05区域( μm)"] =_validate_hundred_scale_score
    registry["35976:感官-眼科光学相干断层扫描仪:右眼视盘中心Choroid层厚度环均分36等分03区域( μm)"] =_validate_hundred_scale_score
    registry["35977:感官-眼科光学相干断层扫描仪:右眼视盘中心Choroid层厚度环均分36等分17区域( μm)"] =_validate_hundred_scale_score
    registry["35978:感官-眼科光学相干断层扫描仪:右眼视盘中心Choroid层厚度环均分36等分35区域( μm)"] =_validate_hundred_scale_score
    registry["35979:感官-眼科光学相干断层扫描仪:右眼视盘中心Choroid层厚度环均分4等分上侧( μm)"] =_validate_hundred_scale_score
    registry["35980:感官-眼科光学相干断层扫描仪:右眼视盘中心Choroid层厚度环均分6等分鼻上侧( μm)"] =_validate_hundred_scale_score
    registry["35981:感官-眼科光学相干断层扫描仪:右眼视盘中心Choroid层厚度环均分6等分颞上侧( μm)"] =_validate_hundred_scale_score
    registry["35982:感官-眼科光学相干断层扫描仪:右眼视盘中心Choroid层厚度环均分12等分上鼻侧( μm)"] =_validate_hundred_scale_score
    registry["35983:感官-眼科光学相干断层扫描仪:右眼视盘中心Choroid层厚度环均分12等分上颞侧( μm)"] =_validate_hundred_scale_score
    registry["35984:感官-眼科光学相干断层扫描仪:右眼视盘中心Choroid层厚度环均分12等分上侧( μm)"] =_validate_hundred_scale_score
    registry["35985:感官-眼科光学相干断层扫描仪:右眼视盘中心Choroid层厚度环均分36等分06区域( μm)"] =_validate_hundred_scale_score
    registry["35986:感官-眼科光学相干断层扫描仪:右眼视盘中心Choroid层厚度环均分36等分07区域( μm)"] =_validate_hundred_scale_score
    registry["35987:感官-眼科光学相干断层扫描仪:右眼视盘中心Choroid层厚度环均分36等分08区域( μm)"] =_validate_hundred_scale_score
    registry["35988:感官-眼科光学相干断层扫描仪:右眼视盘中心Choroid层厚度环均分36等分09区域( μm)"] =_validate_hundred_scale_score
    registry["35989:感官-眼科光学相干断层扫描仪:右眼视盘中心Choroid层厚度环均分36等分10区域( μm)"] =_validate_hundred_scale_score
    registry["35990:感官-眼科光学相干断层扫描仪:右眼视盘中心Choroid层厚度环均分36等分11区域( μm)"] =_validate_hundred_scale_score
    registry["35991:感官-眼科光学相干断层扫描仪:右眼视盘中心Choroid层厚度环均分36等分12区域( μm)"] =_validate_hundred_scale_score
    registry["35992:感官-眼科光学相干断层扫描仪:右眼视盘中心Choroid层厚度环均分36等分13区域( μm)"] =_validate_hundred_scale_score
    registry["35993:感官-眼科光学相干断层扫描仪:右眼视盘中心Choroid层厚度环均分36等分14区域( μm)"] =_validate_hundred_scale_score
    registry["35994:感官-眼科光学相干断层扫描仪:右眼视盘中心Choroid层厚度环均分4等分下侧( μm)"] =_validate_hundred_scale_score
    registry["35995:感官-眼科光学相干断层扫描仪:右眼视盘中心Choroid层厚度环均分4等分鼻侧( μm)"] =_validate_hundred_scale_score
    registry["35996:感官-眼科光学相干断层扫描仪:右眼视盘中心Choroid层厚度环均分4等分颞侧( μm)"] =_validate_hundred_scale_score
    registry["35997:感官-眼科光学相干断层扫描仪:右眼视盘中心Choroid层厚度环均分6等分鼻下侧( μm)"] =_validate_hundred_scale_score
    registry["35998:感官-眼科光学相干断层扫描仪:右眼视盘中心Choroid层厚度环均分6等分鼻侧( μm)"] =_validate_hundred_scale_score
    registry["35999:感官-眼科光学相干断层扫描仪:右眼视盘中心Choroid层厚度环均分6等分颞下侧( μm)"] =_validate_hundred_scale_score
    registry["36000:感官-眼科光学相干断层扫描仪:右眼视盘中心Choroid层厚度环均分6等分颞侧( μm)"] =_validate_hundred_scale_score
    registry["36001:感官-眼科光学相干断层扫描仪:右眼视盘中心Choroid层厚度环均分12等分鼻上侧( μm)"] =_validate_hundred_scale_score
    registry["36002:感官-眼科光学相干断层扫描仪:右眼视盘中心Choroid层厚度环均分12等分鼻下侧( μm)"] =_validate_hundred_scale_score
    registry["36003:感官-眼科光学相干断层扫描仪:右眼视盘中心Choroid层厚度环均分12等分鼻侧( μm)"] =_validate_hundred_scale_score
    registry["36004:感官-眼科光学相干断层扫描仪:右眼视盘中心Choroid层厚度环均分12等分颞下侧( μm)"] =_validate_hundred_scale_score
    registry["36005:感官-眼科光学相干断层扫描仪:右眼视盘中心Choroid层厚度环均分12等分颞侧( μm)"] =_validate_hundred_scale_score
    registry["36006:感官-眼科光学相干断层扫描仪:右眼视盘中心Choroid层厚度环均分12等分下鼻侧( μm)"] =_validate_hundred_scale_score
    registry["36007:感官-眼科光学相干断层扫描仪:右眼视盘中心Choroid层厚度环均分12等分下颞侧( μm)"] =_validate_hundred_scale_score
    registry["36008:感官-眼科光学相干断层扫描仪:右眼视盘中心Choroid层厚度环均分12等分下侧( μm)"] =_validate_hundred_scale_score
    registry["36009:感官-眼科光学相干断层扫描仪:右眼视盘中心Choroid层厚度环均分36等分01区域( μm)"] =_validate_hundred_scale_score
    registry["36010:感官-眼科光学相干断层扫描仪:右眼视盘中心Choroid层厚度环均分36等分02区域( μm)"] =_validate_hundred_scale_score
    registry["36011:感官-眼科光学相干断层扫描仪:右眼视盘中心Choroid层厚度环均分36等分15区域( μm)"] =_validate_hundred_scale_score
    registry["36012:感官-眼科光学相干断层扫描仪:右眼视盘中心Choroid层厚度环均分36等分16区域( μm)"] =_validate_hundred_scale_score
    registry["36013:感官-眼科光学相干断层扫描仪:右眼视盘中心Choroid层厚度环均分36等分18区域( μm)"] =_validate_hundred_scale_score
    registry["36014:感官-眼科光学相干断层扫描仪:右眼视盘中心Choroid层厚度环均分36等分19区域( μm)"] =_validate_hundred_scale_score
    registry["36015:感官-眼科光学相干断层扫描仪:右眼视盘中心Choroid层厚度环均分36等分20区域( μm)"] =_validate_hundred_scale_score
    registry["36016:感官-眼科光学相干断层扫描仪:右眼视盘中心Choroid层厚度环均分36等分21区域( μm)"] =_validate_hundred_scale_score
    registry["36017:感官-眼科光学相干断层扫描仪:右眼视盘中心Choroid层厚度环均分36等分22区域( μm)"] =_validate_hundred_scale_score
    registry["36018:感官-眼科光学相干断层扫描仪:右眼视盘中心Choroid层厚度环均分36等分23区域( μm)"] =_validate_hundred_scale_score
    registry["36019:感官-眼科光学相干断层扫描仪:右眼视盘中心Choroid层厚度环均分36等分24区域( μm)"] =_validate_hundred_scale_score
    registry["36020:感官-眼科光学相干断层扫描仪:右眼视盘中心Choroid层厚度环均分36等分25区域( μm)"] =_validate_hundred_scale_score
    registry["36021:感官-眼科光学相干断层扫描仪:右眼视盘中心Choroid层厚度环均分36等分26区域( μm)"] =_validate_hundred_scale_score
    registry["36022:感官-眼科光学相干断层扫描仪:右眼视盘中心Choroid层厚度环均分36等分27区域( μm)"] =_validate_hundred_scale_score
    registry["36023:感官-眼科光学相干断层扫描仪:右眼视盘中心Choroid层厚度环均分36等分28区域( μm)"] =_validate_hundred_scale_score
    registry["36024:感官-眼科光学相干断层扫描仪:右眼视盘中心Choroid层厚度环均分36等分29区域( μm)"] =_validate_hundred_scale_score
    registry["36025:感官-眼科光学相干断层扫描仪:右眼视盘中心Choroid层厚度环均分36等分30区域( μm)"] =_validate_hundred_scale_score
    registry["36026:感官-眼科光学相干断层扫描仪:右眼视盘中心Choroid层厚度环均分36等分31区域( μm)"] =_validate_hundred_scale_score
    registry["36027:感官-眼科光学相干断层扫描仪:右眼视盘中心Choroid层厚度环均分36等分32区域( μm)"] =_validate_hundred_scale_score
    registry["36028:感官-眼科光学相干断层扫描仪:右眼视盘中心Choroid层厚度环均分36等分33区域( μm)"] =_validate_hundred_scale_score
    registry["36029:感官-眼科光学相干断层扫描仪:右眼视盘中心Choroid层厚度环均分36等分34区域( μm)"] =_validate_hundred_scale_score
    registry["36030:感官-眼科光学相干断层扫描仪:右眼视盘中心Choroid层厚度环均分36等分36区域( μm)"] =_validate_hundred_scale_score
    registry["36031:感官-眼科光学相干断层扫描仪:右眼视盘中心GCL++层厚度平均( μm)"] =_validate_hundred_scale_score
    registry["36032:感官-眼科光学相干断层扫描仪:右眼视盘中心GCL++层厚度环均分12等分上鼻侧( μm)"] =_validate_hundred_scale_score
    registry["36033:感官-眼科光学相干断层扫描仪:右眼视盘中心RNFL层厚度环均分12等分下鼻侧( μm)"] =_validate_hundred_scale_score
    registry["36034:感官-眼科光学相干断层扫描仪:右眼视盘中心RNFL层厚度环均分36等分25区域( μm)"] =_validate_hundred_scale_score
    registry["36035:感官-眼科光学相干断层扫描仪:右眼视盘中心GCL++层厚度环均分12等分下鼻侧( μm)"] =_validate_hundred_scale_score
    registry["36036:感官-眼科光学相干断层扫描仪:右眼视盘中心GCL++层厚度环均分36等分25区域( μm)"] =_validate_hundred_scale_score
    registry["36037:感官-眼科光学相干断层扫描仪:右眼视盘中心GCL++层厚度环均分12等分鼻下侧( μm)"] =_validate_hundred_scale_score
    registry["36038:感官-眼科光学相干断层扫描仪:右眼视盘中心GCL++层厚度环均分12等分鼻侧( μm)"] =_validate_hundred_scale_score
    registry["36039:感官-眼科光学相干断层扫描仪:右眼视盘中心GCL++层厚度环均分36等分19区域( μm)"] =_validate_hundred_scale_score
    registry["36040:感官-眼科光学相干断层扫描仪:右眼视盘中心RNFL层厚度环均分12等分上侧( μm)"] =_validate_hundred_scale_score
    registry["36041:感官-眼科光学相干断层扫描仪:右眼视盘中心RNFL层厚度环均分36等分10区域( μm)"] =_validate_hundred_scale_score
    registry["36042:感官-眼科光学相干断层扫描仪:右眼视盘中心GCL++层厚度环均分12等分上侧( μm)"] =_validate_hundred_scale_score
    registry["36043:感官-眼科光学相干断层扫描仪:右眼视盘中心GCL++层厚度环均分36等分10区域( μm)"] =_validate_hundred_scale_score
    registry["36044:感官-眼科光学相干断层扫描仪:右眼视盘中心GCL++层厚度环均分36等分12区域( μm)"] =_validate_hundred_scale_score
    registry["36045:感官-眼科光学相干断层扫描仪:右眼视盘中心GCL++层厚度环均分36等分15区域( μm)"] =_validate_hundred_scale_score
    registry["36046:感官-眼科光学相干断层扫描仪:右眼视盘中心RNFL层厚度环均分36等分16区域( μm)"] =_validate_hundred_scale_score
    registry["36047:感官-眼科光学相干断层扫描仪:右眼视盘中心GCL++层厚度环均分12等分鼻上侧( μm)"] =_validate_hundred_scale_score
    registry["36048:感官-眼科光学相干断层扫描仪:右眼视盘中心GCL++层厚度环均分36等分16区域( μm)"] =_validate_hundred_scale_score
    registry["36049:感官-眼科光学相干断层扫描仪:右眼视盘中心GCL++层厚度环均分36等分17区域( μm)"] =_validate_hundred_scale_score
    registry["36050:感官-眼科光学相干断层扫描仪:右眼视盘中心GCL++层厚度环均分36等分18区域( μm)"] =_validate_hundred_scale_score
    registry["36051:感官-眼科光学相干断层扫描仪:右眼视盘中心GCL++层厚度环均分36等分20区域( μm)"] =_validate_hundred_scale_score
    registry["36052:感官-眼科光学相干断层扫描仪:右眼视盘中心GCL++层厚度环均分36等分21区域( μm)"] =_validate_hundred_scale_score
    registry["36053:感官-眼科光学相干断层扫描仪:右眼视盘中心GCL++层厚度环均分36等分22区域( μm)"] =_validate_hundred_scale_score
    registry["36054:感官-眼科光学相干断层扫描仪:右眼视盘中心GCL++层厚度环均分36等分23区域( μm)"] =_validate_hundred_scale_score
    registry["36055:感官-眼科光学相干断层扫描仪:右眼视盘中心GCL++层厚度环均分36等分29区域( μm)"] =_validate_hundred_scale_score
    registry["36056:感官-眼科光学相干断层扫描仪:右眼视盘中心GCL+层厚度平均( μm)"] =_validate_hundred_scale_score
    registry["36057:感官-眼科光学相干断层扫描仪:右眼视盘中心GCL+层厚度环均分12等分颞上侧( μm)"] =_validate_hundred_scale_score
    registry["36058:感官-眼科光学相干断层扫描仪:右眼视盘中心GCL+层厚度环均分36等分04区域( μm)"] =_validate_hundred_scale_score
    registry["36059:感官-眼科光学相干断层扫描仪:右眼视盘中心GCL+层厚度环均分12等分鼻侧( μm)"] =_validate_hundred_scale_score
    registry["36060:感官-眼科光学相干断层扫描仪:右眼视盘中心GCL+层厚度环均分36等分03区域( μm)"] =_validate_hundred_scale_score
    registry["36061:感官-眼科光学相干断层扫描仪:右眼视盘中心GCL+层厚度环均分36等分05区域( μm)"] =_validate_hundred_scale_score
    registry["36062:感官-眼科光学相干断层扫描仪:右眼视盘中心GCL+层厚度环均分36等分06区域( μm)"] =_validate_hundred_scale_score
    registry["36063:感官-眼科光学相干断层扫描仪:右眼视盘中心GCL+层厚度环均分36等分07区域( μm)"] =_validate_hundred_scale_score
    registry["36064:感官-眼科光学相干断层扫描仪:右眼视盘中心GCL+层厚度环均分36等分17区域( μm)"] =_validate_hundred_scale_score
    registry["36065:感官-眼科光学相干断层扫描仪:右眼视盘中心GCL+层厚度环均分36等分18区域( μm)"] =_validate_hundred_scale_score
    registry["36066:感官-眼科光学相干断层扫描仪:右眼视盘中心GCL+层厚度环均分36等分19区域( μm)"] =_validate_hundred_scale_score
    registry["36067:感官-眼科光学相干断层扫描仪:右眼视盘中心GCL+层厚度环均分36等分20区域( μm)"] =_validate_hundred_scale_score
    registry["36068:感官-眼科光学相干断层扫描仪:右眼视盘中心GCL+层厚度环均分36等分21区域( μm)"] =_validate_hundred_scale_score
    registry["36069:感官-眼科光学相干断层扫描仪:右眼视盘中心GCL+层厚度环均分36等分31区域( μm)"] =_validate_hundred_scale_score
    registry["36070:感官-眼科光学相干断层扫描仪:右眼视盘中心GCL+层厚度环均分36等分32区域( μm)"] =_validate_hundred_scale_score
    registry["36071:感官-眼科光学相干断层扫描仪:右眼视盘中心GCL+层厚度环均分36等分33区域( μm)"] =_validate_hundred_scale_score
    registry["36072:感官-眼科光学相干断层扫描仪:右眼视盘中心GCL+层厚度环均分36等分35区域( μm)"] =_validate_hundred_scale_score
    registry["36073:感官-眼科光学相干断层扫描仪:右眼视盘中心GCL+层厚度环均分4等分颞侧( μm)"] =_validate_hundred_scale_score
    registry["36074:感官-眼科光学相干断层扫描仪:右眼视盘中心GCL+层厚度环均分6等分颞侧( μm)"] =_validate_hundred_scale_score
    registry["36075:感官-眼科光学相干断层扫描仪:右眼视盘中心GCL+层厚度环均分12等分颞下侧( μm)"] =_validate_hundred_scale_score
    registry["36076:感官-眼科光学相干断层扫描仪:右眼视盘中心GCL+层厚度环均分12等分颞侧( μm)"] =_validate_hundred_scale_score
    registry["36077:感官-眼科光学相干断层扫描仪:右眼视盘中心GCL+层厚度环均分36等分01区域( μm)"] =_validate_hundred_scale_score
    registry["36078:感官-眼科光学相干断层扫描仪:右眼视盘中心GCL+层厚度环均分36等分02区域( μm)"] =_validate_hundred_scale_score
    registry["36079:感官-眼科光学相干断层扫描仪:右眼视盘中心GCL+层厚度环均分36等分34区域( μm)"] =_validate_hundred_scale_score
    registry["36080:感官-眼科光学相干断层扫描仪:右眼视盘中心GCL+层厚度环均分36等分36区域( μm)"] =_validate_hundred_scale_score
    registry["36081:感官-眼科光学相干断层扫描仪:右眼视盘中心GCL+层厚度环均分6等分颞下侧( μm)"] =_validate_hundred_scale_score
    registry["36082:感官-眼科光学相干断层扫描仪:右眼视盘中心GCL+层厚度环均分12等分下颞侧( μm)"] =_validate_hundred_scale_score
    registry["36083:感官-眼科光学相干断层扫描仪:右眼视盘中心RNFL层厚度平均( μm)"] =_validate_hundred_scale_score
    registry["36084:感官-眼科光学相干断层扫描仪:右眼视盘中心RNFL层厚度环均分12等分颞下侧( μm)"] =_validate_hundred_scale_score
    registry["36085:感官-眼科光学相干断层扫描仪:右眼视盘中心RNFL层厚度环均分36等分34区域( μm)"] =_validate_hundred_scale_score
    registry["36086:感官-眼科光学相干断层扫描仪:右眼视盘中心RNFL层厚度环均分12等分颞侧( μm)"] =_validate_hundred_scale_score
    registry["36087:感官-眼科光学相干断层扫描仪:右眼视盘中心RNFL层厚度环均分36等分01区域( μm)"] =_validate_hundred_scale_score
    registry["36088:感官-眼科光学相干断层扫描仪:右眼视盘中心RNFL层厚度环均分36等分02区域( μm)"] =_validate_hundred_scale_score
    registry["36089:感官-眼科光学相干断层扫描仪:右眼视盘中心RNFL层厚度环均分12等分鼻上侧( μm)"] =_validate_hundred_scale_score
    registry["36090:感官-眼科光学相干断层扫描仪:右眼视盘中心RNFL层厚度环均分12等分鼻下侧( μm)"] =_validate_hundred_scale_score
    registry["36091:感官-眼科光学相干断层扫描仪:右眼视盘中心RNFL层厚度环均分36等分22区域( μm)"] =_validate_hundred_scale_score
    registry["36092:感官-眼科光学相干断层扫描仪:右眼视盘中心RNFL层厚度环均分12等分鼻侧( μm)"] =_validate_hundred_scale_score
    registry["36093:感官-眼科光学相干断层扫描仪:右眼视盘中心RNFL层厚度环均分36等分19区域( μm)"] =_validate_hundred_scale_score
    registry["36094:感官-眼科光学相干断层扫描仪:右眼视盘中心RNFL层厚度环均分36等分03区域( μm)"] =_validate_hundred_scale_score
    registry["36095:感官-眼科光学相干断层扫描仪:右眼视盘中心RNFL层厚度环均分36等分08区域( μm)"] =_validate_hundred_scale_score
    registry["36096:感官-眼科光学相干断层扫描仪:右眼视盘中心GCL++层厚度环均分36等分08区域( μm)"] =_validate_hundred_scale_score
    registry["36097:感官-眼科光学相干断层扫描仪:右眼视盘中心RNFL层厚度环均分36等分09区域( μm)"] =_validate_hundred_scale_score
    registry["36098:感官-眼科光学相干断层扫描仪:右眼视盘中心GCL++层厚度环均分36等分09区域( μm)"] =_validate_hundred_scale_score
    registry["36099:感官-眼科光学相干断层扫描仪:右眼视盘中心RNFL层厚度环均分36等分11区域( μm)"] =_validate_hundred_scale_score
    registry["36100:感官-眼科光学相干断层扫描仪:右眼视盘中心GCL++层厚度环均分36等分11区域( μm)"] =_validate_hundred_scale_score
    registry["36101:感官-眼科光学相干断层扫描仪:右眼视盘中心RNFL层厚度环均分36等分12区域( μm)"] =_validate_hundred_scale_score
    registry["36102:感官-眼科光学相干断层扫描仪:右眼视盘中心RNFL层厚度环均分12等分上鼻侧( μm)"] =_validate_hundred_scale_score
    registry["36103:感官-眼科光学相干断层扫描仪:右眼视盘中心RNFL层厚度环均分36等分13区域( μm)"] =_validate_hundred_scale_score
    registry["36104:感官-眼科光学相干断层扫描仪:右眼视盘中心GCL++层厚度环均分36等分13区域( μm)"] =_validate_hundred_scale_score
    registry["36105:感官-眼科光学相干断层扫描仪:右眼视盘中心RNFL层厚度环均分36等分14区域( μm)"] =_validate_hundred_scale_score
    registry["36106:感官-眼科光学相干断层扫描仪:右眼视盘中心GCL++层厚度环均分36等分14区域( μm)"] =_validate_hundred_scale_score
    registry["36107:感官-眼科光学相干断层扫描仪:右眼视盘中心RNFL层厚度环均分36等分15区域( μm)"] =_validate_hundred_scale_score
    registry["36108:感官-眼科光学相干断层扫描仪:右眼视盘中心RNFL层厚度环均分36等分17区域( μm)"] =_validate_hundred_scale_score
    registry["36109:感官-眼科光学相干断层扫描仪:右眼视盘中心RNFL层厚度环均分36等分18区域( μm)"] =_validate_hundred_scale_score
    registry["36110:感官-眼科光学相干断层扫描仪:右眼视盘中心RNFL层厚度环均分36等分20区域( μm)"] =_validate_hundred_scale_score
    registry["36111:感官-眼科光学相干断层扫描仪:右眼视盘中心RNFL层厚度环均分36等分21区域( μm)"] =_validate_hundred_scale_score
    registry["36112:感官-眼科光学相干断层扫描仪:右眼视盘中心RNFL层厚度环均分36等分23区域( μm)"] =_validate_hundred_scale_score
    registry["36113:感官-眼科光学相干断层扫描仪:右眼视盘中心RNFL层厚度环均分36等分24区域( μm)"] =_validate_hundred_scale_score
    registry["36114:感官-眼科光学相干断层扫描仪:右眼视盘中心GCL++层厚度环均分36等分24区域( μm)"] =_validate_hundred_scale_score
    registry["36115:感官-眼科光学相干断层扫描仪:右眼视盘中心RNFL层厚度环均分36等分29区域( μm)"] =_validate_hundred_scale_score
    registry["36116:感官-眼科光学相干断层扫描仪:右眼视盘中心RNFL层厚度环均分36等分35区域( μm)"] =_validate_hundred_scale_score
    registry["36117:感官-眼科光学相干断层扫描仪:右眼视盘中心RNFL层厚度环均分36等分36区域( μm)"] =_validate_hundred_scale_score
    registry["36118:感官-眼科光学相干断层扫描仪:右眼视盘中心RNFL层厚度环均分4等分上侧( μm)"] =_validate_hundred_scale_score
    registry["36119:感官-眼科光学相干断层扫描仪:右眼视盘中心GCL++层厚度环均分4等分上侧( μm)"] =_validate_hundred_scale_score
    registry["36120:感官-眼科光学相干断层扫描仪:右眼视盘中心RNFL层厚度环均分4等分下侧( μm)"] =_validate_hundred_scale_score
    registry["36121:感官-眼科光学相干断层扫描仪:右眼视盘中心GCL++层厚度环均分4等分下侧( μm)"] =_validate_hundred_scale_score
    registry["36122:感官-眼科光学相干断层扫描仪:右眼视盘中心RNFL层厚度环均分4等分颞侧( μm)"] =_validate_hundred_scale_score
    registry["36123:感官-眼科光学相干断层扫描仪:右眼视盘中心RNFL层厚度环均分6等分颞侧( μm)"] =_validate_hundred_scale_score
    registry["36124:感官-眼科光学相干断层扫描仪:右眼视盘中心RNFL层厚度环均分6等分鼻上侧( μm)"] =_validate_hundred_scale_score
    registry["36125:感官-眼科光学相干断层扫描仪:右眼视盘中心GCL++层厚度环均分6等分鼻上侧( μm)"] =_validate_hundred_scale_score
    registry["36126:感官-眼科光学相干断层扫描仪:右眼视盘中心RNFL层厚度环均分6等分鼻下侧( μm)"] =_validate_hundred_scale_score
    registry["36127:感官-眼科光学相干断层扫描仪:右眼视盘中心RNFL层厚度环均分36等分26区域( μm)"] =_validate_hundred_scale_score
    registry["36128:感官-眼科光学相干断层扫描仪:右眼视盘中心RNFL层厚度环均分36等分27区域( μm)"] =_validate_hundred_scale_score
    registry["36129:感官-眼科光学相干断层扫描仪:右眼视盘中心GCL++层厚度环均分6等分鼻下侧( μm)"] =_validate_hundred_scale_score
    registry["36130:感官-眼科光学相干断层扫描仪:右眼视盘中心GCL++层厚度环均分36等分26区域( μm)"] =_validate_hundred_scale_score
    registry["36131:感官-眼科光学相干断层扫描仪:右眼视盘中心GCL++层厚度环均分36等分27区域( μm)"] =_validate_hundred_scale_score
    registry["36132:感官-眼科光学相干断层扫描仪:右眼视盘中心RNFL层厚度环均分4等分鼻侧( μm)"] =_validate_hundred_scale_score
    registry["36133:感官-眼科光学相干断层扫描仪:右眼视盘中心RNFL层厚度环均分6等分鼻侧( μm)"] =_validate_hundred_scale_score
    registry["36134:感官-眼科光学相干断层扫描仪:右眼视盘中心GCL++层厚度环均分4等分鼻侧( μm)"] =_validate_hundred_scale_score
    registry["36135:感官-眼科光学相干断层扫描仪:右眼视盘中心GCL++层厚度环均分6等分鼻侧( μm)"] =_validate_hundred_scale_score
    registry["36136:感官-眼科光学相干断层扫描仪:右眼视盘中心Retina层厚度平均( μm)"] =_validate_hundred_scale_score
    registry["36137:感官-眼科光学相干断层扫描仪:右眼视盘中心Retina层厚度环均分12等分上侧( μm)"] =_validate_hundred_scale_score
    registry["36138:感官-眼科光学相干断层扫描仪:右眼视盘中心Retina层厚度环均分36等分09区域( μm)"] =_validate_hundred_scale_score
    registry["36139:感官-眼科光学相干断层扫描仪:右眼视盘中心Retina层厚度环均分36等分10区域( μm)"] =_validate_hundred_scale_score
    registry["36140:感官-眼科光学相干断层扫描仪:右眼视盘中心Retina层厚度环均分12等分上鼻侧( μm)"] =_validate_hundred_scale_score
    registry["36141:感官-眼科光学相干断层扫描仪:右眼视盘中心Retina层厚度环均分36等分13区域( μm)"] =_validate_hundred_scale_score
    registry["36142:感官-眼科光学相干断层扫描仪:右眼视盘中心Retina层厚度环均分36等分14区域( μm)"] =_validate_hundred_scale_score
    registry["36143:感官-眼科光学相干断层扫描仪:右眼视盘中心Retina层厚度环均分6等分鼻下侧( μm)"] =_validate_hundred_scale_score
    registry["36144:感官-眼科光学相干断层扫描仪:右眼视盘中心Retina层厚度环均分12等分下侧( μm)"] =_validate_hundred_scale_score
    registry["36145:感官-眼科光学相干断层扫描仪:右眼视盘中心Retina层厚度环均分36等分26区域( μm)"] =_validate_hundred_scale_score
    registry["36146:感官-眼科光学相干断层扫描仪:右眼视盘中心Retina层厚度环均分36等分27区域( μm)"] =_validate_hundred_scale_score
    registry["36147:感官-眼科光学相干断层扫描仪:右眼视盘中心Retina层厚度环均分36等分28区域( μm)"] =_validate_hundred_scale_score
    registry["36148:感官-眼科光学相干断层扫描仪:右眼视盘中心Retina层厚度环均分36等分29区域( μm)"] =_validate_hundred_scale_score
    registry["36149:感官-眼科光学相干断层扫描仪:右眼视盘中心RNFL层厚度环均分12等分下侧( μm)"] =_validate_hundred_scale_score
    registry["36150:感官-眼科光学相干断层扫描仪:右眼视盘中心RNFL层厚度环均分36等分28区域( μm)"] =_validate_hundred_scale_score
    registry["36151:感官-眼科光学相干断层扫描仪:右眼视盘中心GCL++层厚度环均分12等分下侧( μm)"] =_validate_hundred_scale_score
    registry["36152:感官-眼科光学相干断层扫描仪:右眼视盘中心GCL++层厚度环均分36等分28区域( μm)"] =_validate_hundred_scale_score
    registry["36153:感官-眼科光学相干断层扫描仪:右眼视盘中心Retina层厚度环均分12等分下鼻侧( μm)"] =_validate_hundred_scale_score
    registry["36154:感官-眼科光学相干断层扫描仪:右眼视盘中心Retina层厚度环均分36等分25区域( μm)"] =_validate_hundred_scale_score
    registry["36155:感官-眼科光学相干断层扫描仪:右眼视盘中心Retina层厚度环均分12等分鼻上侧( μm)"] =_validate_hundred_scale_score
    registry["36156:感官-眼科光学相干断层扫描仪:右眼视盘中心Retina层厚度环均分36等分15区域( μm)"] =_validate_hundred_scale_score
    registry["36157:感官-眼科光学相干断层扫描仪:右眼视盘中心Retina层厚度环均分36等分16区域( μm)"] =_validate_hundred_scale_score
    registry["36158:感官-眼科光学相干断层扫描仪:右眼视盘中心Retina层厚度环均分12等分鼻下侧( μm)"] =_validate_hundred_scale_score
    registry["36159:感官-眼科光学相干断层扫描仪:右眼视盘中心Retina层厚度环均分36等分22区域( μm)"] =_validate_hundred_scale_score
    registry["36160:感官-眼科光学相干断层扫描仪:右眼视盘中心Retina层厚度环均分36等分23区域( μm)"] =_validate_hundred_scale_score
    registry["36161:感官-眼科光学相干断层扫描仪:右眼视盘中心Retina层厚度环均分12等分鼻侧( μm)"] =_validate_hundred_scale_score
    registry["36162:感官-眼科光学相干断层扫描仪:右眼视盘中心Retina层厚度环均分36等分19区域( μm)"] =_validate_hundred_scale_score
    registry["36163:感官-眼科光学相干断层扫描仪:右眼视盘中心Retina层厚度环均分36等分08区域( μm)"] =_validate_hundred_scale_score
    registry["36164:感官-眼科光学相干断层扫描仪:右眼视盘中心Retina层厚度环均分36等分17区域( μm)"] =_validate_hundred_scale_score
    registry["36165:感官-眼科光学相干断层扫描仪:右眼视盘中心Retina层厚度环均分36等分18区域( μm)"] =_validate_hundred_scale_score
    registry["36166:感官-眼科光学相干断层扫描仪:右眼视盘中心Retina层厚度环均分36等分20区域( μm)"] =_validate_hundred_scale_score
    registry["36167:感官-眼科光学相干断层扫描仪:右眼视盘中心Retina层厚度环均分36等分21区域( μm)"] =_validate_hundred_scale_score
    registry["36168:感官-眼科光学相干断层扫描仪:右眼视盘中心Retina层厚度环均分36等分24区域( μm)"] =_validate_hundred_scale_score
    registry["36169:感官-眼科光学相干断层扫描仪:右眼视盘中心Retina层厚度环均分4等分上侧( μm)"] =_validate_hundred_scale_score
    registry["36170:感官-眼科光学相干断层扫描仪:右眼视盘中心Retina层厚度环均分4等分下侧( μm)"] =_validate_hundred_scale_score
    registry["36171:感官-眼科光学相干断层扫描仪:右眼视盘中心Retina层厚度环均分4等分鼻侧( μm)"] =_validate_hundred_scale_score
    registry["36172:感官-眼科光学相干断层扫描仪:右眼视盘中心Retina层厚度环均分6等分鼻侧( μm)"] =_validate_hundred_scale_score
    registry["36173:感官-眼科光学相干断层扫描仪:右眼视盘中心Retina层厚度环均分6等分鼻上侧( μm)"] =_validate_hundred_scale_score
    registry["36174:感官-眼科光学相干断层扫描仪:右眼视盘中心Retina层厚度环均分36等分11区域( μm)"] =_validate_hundred_scale_score
    registry["36175:感官-眼科光学相干断层扫描仪:右眼视盘中心Retina层厚度环均分36等分12区域( μm)"] =_validate_hundred_scale_score
    registry["36176:感官-眼科光学相干断层扫描仪:右眼视盘垂直直径(mm)"] =_validate_hundred_scale_score
    registry["36177:感官-眼科光学相干断层扫描仪:右眼视盘水平直径(mm)"] =_validate_hundred_scale_score
    registry["36178:感官-眼科光学相干断层扫描仪:右眼视盘面积(mm2)"] =_validate_hundred_scale_score
    registry["36179:感官-眼科光学相干断层扫描仪:右眼颞侧视盘中心外层密度(%)"] = _validate_hundred_scale_score
    registry["36180:感官-眼科光学相干断层扫描仪:右眼颞侧视盘中心浅层密度(%)"] = _validate_hundred_scale_score
    registry["36181:感官-眼科光学相干断层扫描仪:右眼颞侧视盘中心深层密度(%)"] = _validate_hundred_scale_score
    registry["36182:感官-眼科光学相干断层扫描仪:右眼颞侧视盘中心脉络膜层密度(%)"] =_validate_hundred_scale_score
    registry["36183:感官-眼科光学相干断层扫描仪:右眼黄斑中心Choroid层厚度中心( μm)"] =_validate_hundred_scale_score
    registry["36184:感官-眼科光学相干断层扫描仪:右眼黄斑中心Choroid层厚度平均( μm)"] =_validate_hundred_scale_score
    registry["36185:感官-眼科光学相干断层扫描仪:右眼黄斑中心Choroid层厚度内环上侧( μm)"] =_validate_hundred_scale_score
    registry["36186:感官-眼科光学相干断层扫描仪:右眼黄斑中心Choroid层厚度内环下侧( μm)"] =_validate_hundred_scale_score
    registry["36187:感官-眼科光学相干断层扫描仪:右眼黄斑中心Choroid层厚度外环下侧( μm)"] =_validate_hundred_scale_score
    registry["36188:感官-眼科光学相干断层扫描仪:右眼黄斑中心Choroid层厚度内环颞侧( μm)"] =_validate_hundred_scale_score
    registry["36189:感官-眼科光学相干断层扫描仪:右眼黄斑中心Choroid层厚度外环颞侧( μm)"] =_validate_hundred_scale_score
    registry["36190:感官-眼科光学相干断层扫描仪:右眼黄斑中心Choroid层厚度内环鼻侧( μm)"] =_validate_hundred_scale_score
    registry["36191:感官-眼科光学相干断层扫描仪:右眼黄斑中心Choroid层厚度外环上侧( μm)"] =_validate_hundred_scale_score
    registry["36192:感官-眼科光学相干断层扫描仪:右眼黄斑中心Choroid层厚度外环鼻侧( μm)"] =_validate_hundred_scale_score
    registry["36193:感官-眼科光学相干断层扫描仪:右眼鼻侧视盘中心外层密度(%)"] = _validate_hundred_scale_score
    registry["36194:感官-眼科光学相干断层扫描仪:右眼鼻侧视盘中心浅层密度(%)"] = _validate_hundred_scale_score
    registry["36195:感官-眼科光学相干断层扫描仪:右眼鼻侧视盘中心深层密度(%)"] = _validate_hundred_scale_score
    registry["36196:感官-眼科光学相干断层扫描仪:右眼鼻侧视盘中心脉络膜层密度(%)"] = _validate_hundred_scale_score
    registry["36197:感官-眼科光学相干断层扫描仪:左眼上侧视盘中心外层密度(%)"] = _validate_hundred_scale_score
    registry["36198:感官-眼科光学相干断层扫描仪:左眼上侧视盘中心浅层密度(%)"] = _validate_hundred_scale_score
    registry["36199:感官-眼科光学相干断层扫描仪:左眼上侧视盘中心深层密度(%)"] = _validate_hundred_scale_score
    registry["36200:感官-眼科光学相干断层扫描仪:左眼上侧视盘中心脉络膜层密度(%)"] = _validate_hundred_scale_score
    registry["36201:感官-眼科光学相干断层扫描仪:左眼下侧视盘中心外层密度(%)"] = _validate_hundred_scale_score
    registry["36202:感官-眼科光学相干断层扫描仪:左眼下侧视盘中心浅层密度(%)"] = _validate_hundred_scale_score
    registry["36203:感官-眼科光学相干断层扫描仪:左眼下侧视盘中心深层密度(%)"] = _validate_hundred_scale_score
    registry["36204:感官-眼科光学相干断层扫描仪:左眼下侧视盘中心脉络膜层密度(%)"] = _validate_hundred_scale_score
    registry["36205:感官-眼科光学相干断层扫描仪:左眼中心视盘中心外层密度(%)"] = _validate_hundred_scale_score
    registry["36206:感官-眼科光学相干断层扫描仪:左眼中心视盘中心浅层密度(%)"] = _validate_hundred_scale_score
    registry["36207:感官-眼科光学相干断层扫描仪:左眼中心视盘中心深层密度(%)"] = _validate_hundred_scale_score
    registry["36208:感官-眼科光学相干断层扫描仪:左眼中心视盘中心脉络膜层密度(%)"] = _validate_hundred_scale_score
    registry["36209:感官-眼科光学相干断层扫描仪:左眼盘沿体积(mm3)"] =_validate_hundred_scale_score
    registry["36210:感官-眼科光学相干断层扫描仪:左眼盘沿面积(mm2)"] =_validate_hundred_scale_score
    registry["36211:感官-眼科光学相干断层扫描仪:左眼视杯与视盘面积比率"] =_validate_hundred_scale_score
    registry["36212:感官-眼科光学相干断层扫描仪:左眼视杯与视盘面积比率的平方根"] =_validate_hundred_scale_score
    registry["36213:感官-眼科光学相干断层扫描仪:左眼视杯与视盘纵向直径比率"] =_validate_hundred_scale_score
    registry["36214:感官-眼科光学相干断层扫描仪:左眼视杯体积(mm3)"] =_validate_hundred_scale_score
    registry["36215:感官-眼科光学相干断层扫描仪:左眼视杯面积(mm2)"] =_validate_hundred_scale_score
    registry["36216:感官-眼科光学相干断层扫描仪:左眼视盘中心Choroid层厚度平均( μm)"] =_validate_hundred_scale_score
    registry["36217:感官-眼科光学相干断层扫描仪:左眼视盘中心Choroid层厚度环均分36等分21区域( μm)"] =_validate_hundred_scale_score
    registry["36218:感官-眼科光学相干断层扫描仪:左眼视盘中心Choroid层厚度环均分36等分35区域( μm)"] =_validate_hundred_scale_score
    registry["36219:感官-眼科光学相干断层扫描仪:左眼视盘中心Choroid层厚度环均分4等分上侧( μm)"] =_validate_hundred_scale_score
    registry["36220:感官-眼科光学相干断层扫描仪:左眼视盘中心Choroid层厚度环均分4等分鼻侧( μm)"] =_validate_hundred_scale_score
    registry["36221:感官-眼科光学相干断层扫描仪:左眼视盘中心Choroid层厚度环均分6等分鼻上侧( μm)"] =_validate_hundred_scale_score
    registry["36222:感官-眼科光学相干断层扫描仪:左眼视盘中心Choroid层厚度环均分6等分鼻侧( μm)"] =_validate_hundred_scale_score
    registry["36223:感官-眼科光学相干断层扫描仪:左眼视盘中心Choroid层厚度环均分6等分颞上侧( μm)"] =_validate_hundred_scale_score
    registry["36224:感官-眼科光学相干断层扫描仪:左眼视盘中心Choroid层厚度环均分12等分鼻上侧( μm)"] =_validate_hundred_scale_score
    registry["36225:感官-眼科光学相干断层扫描仪:左眼视盘中心Choroid层厚度环均分12等分鼻下侧( μm)"] =_validate_hundred_scale_score
    registry["36226:感官-眼科光学相干断层扫描仪:左眼视盘中心Choroid层厚度环均分12等分鼻侧( μm)"] =_validate_hundred_scale_score
    registry["36227:感官-眼科光学相干断层扫描仪:左眼视盘中心Choroid层厚度环均分12等分上鼻侧( μm)"] =_validate_hundred_scale_score
    registry["36228:感官-眼科光学相干断层扫描仪:左眼视盘中心Choroid层厚度环均分12等分上颞侧( μm)"] =_validate_hundred_scale_score
    registry["36229:感官-眼科光学相干断层扫描仪:左眼视盘中心Choroid层厚度环均分12等分上侧( μm)"] =_validate_hundred_scale_score
    registry["36230:感官-眼科光学相干断层扫描仪:左眼视盘中心Choroid层厚度环均分36等分05区域( μm)"] =_validate_hundred_scale_score
    registry["36231:感官-眼科光学相干断层扫描仪:左眼视盘中心Choroid层厚度环均分36等分06区域( μm)"] =_validate_hundred_scale_score
    registry["36232:感官-眼科光学相干断层扫描仪:左眼视盘中心Choroid层厚度环均分36等分07区域( μm)"] =_validate_hundred_scale_score
    registry["36233:感官-眼科光学相干断层扫描仪:左眼视盘中心Choroid层厚度环均分36等分08区域( μm)"] =_validate_hundred_scale_score
    registry["36234:感官-眼科光学相干断层扫描仪:左眼视盘中心Choroid层厚度环均分36等分09区域( μm)"] =_validate_hundred_scale_score
    registry["36235:感官-眼科光学相干断层扫描仪:左眼视盘中心Choroid层厚度环均分36等分10区域( μm)"] =_validate_hundred_scale_score
    registry["36236:感官-眼科光学相干断层扫描仪:左眼视盘中心Choroid层厚度环均分36等分11区域( μm)"] =_validate_hundred_scale_score
    registry["36237:感官-眼科光学相干断层扫描仪:左眼视盘中心Choroid层厚度环均分36等分12区域( μm)"] =_validate_hundred_scale_score
    registry["36238:感官-眼科光学相干断层扫描仪:左眼视盘中心Choroid层厚度环均分36等分13区域( μm)"] =_validate_hundred_scale_score
    registry["36239:感官-眼科光学相干断层扫描仪:左眼视盘中心Choroid层厚度环均分36等分14区域( μm)"] =_validate_hundred_scale_score
    registry["36240:感官-眼科光学相干断层扫描仪:左眼视盘中心Choroid层厚度环均分36等分15区域( μm)"] =_validate_hundred_scale_score
    registry["36241:感官-眼科光学相干断层扫描仪:左眼视盘中心Choroid层厚度环均分36等分16区域( μm)"] =_validate_hundred_scale_score
    registry["36242:感官-眼科光学相干断层扫描仪:左眼视盘中心Choroid层厚度环均分36等分17区域( μm)"] =_validate_hundred_scale_score
    registry["36243:感官-眼科光学相干断层扫描仪:左眼视盘中心Choroid层厚度环均分36等分18区域( μm)"] =_validate_hundred_scale_score
    registry["36244:感官-眼科光学相干断层扫描仪:左眼视盘中心Choroid层厚度环均分36等分19区域( μm)"] =_validate_hundred_scale_score
    registry["36245:感官-眼科光学相干断层扫描仪:左眼视盘中心Choroid层厚度环均分36等分20区域( μm)"] =_validate_hundred_scale_score
    registry["36246:感官-眼科光学相干断层扫描仪:左眼视盘中心Choroid层厚度环均分36等分22区域( μm)"] = _validate_hundred_scale_score
    registry["36247:感官-眼科光学相干断层扫描仪:左眼视盘中心Choroid层厚度环均分36等分23区域( μm)"] =_validate_hundred_scale_score
    registry["36248:感官-眼科光学相干断层扫描仪:左眼视盘中心Choroid层厚度环均分4等分下侧( μm)"] =_validate_hundred_scale_score
    registry["36249:感官-眼科光学相干断层扫描仪:左眼视盘中心Choroid层厚度环均分4等分颞侧( μm)"] =_validate_hundred_scale_score
    registry["36250:感官-眼科光学相干断层扫描仪:左眼视盘中心Choroid层厚度环均分6等分鼻下侧( μm)"] =_validate_hundred_scale_score
    registry["36251:感官-眼科光学相干断层扫描仪:左眼视盘中心Choroid层厚度环均分6等分颞下侧( μm)"] =_validate_hundred_scale_score
    registry["36252:感官-眼科光学相干断层扫描仪:左眼视盘中心Choroid层厚度环均分6等分颞侧( μm)"] =_validate_hundred_scale_score
    registry["36253:感官-眼科光学相干断层扫描仪:左眼视盘中心Choroid层厚度环均分12等分颞上侧( μm)"] =_validate_hundred_scale_score
    registry["36254:感官-眼科光学相干断层扫描仪:左眼视盘中心Choroid层厚度环均分12等分颞下侧( μm)"] =_validate_hundred_scale_score
    registry["36255:感官-眼科光学相干断层扫描仪:左眼视盘中心Choroid层厚度环均分12等分颞侧( μm)"] =_validate_hundred_scale_score
    registry["36256:感官-眼科光学相干断层扫描仪:左眼视盘中心Choroid层厚度环均分12等分下鼻侧( μm)"] =_validate_hundred_scale_score
    registry["36257:感官-眼科光学相干断层扫描仪:左眼视盘中心Choroid层厚度环均分12等分下颞侧( μm)"] =_validate_hundred_scale_score
    registry["36258:感官-眼科光学相干断层扫描仪:左眼视盘中心Choroid层厚度环均分12等分下侧( μm)"] =_validate_hundred_scale_score
    registry["36259:感官-眼科光学相干断层扫描仪:左眼视盘中心Choroid层厚度环均分36等分01区域( μm)"] =_validate_hundred_scale_score
    registry["36260:感官-眼科光学相干断层扫描仪:左眼视盘中心Choroid层厚度环均分36等分02区域( μm)"] =_validate_hundred_scale_score
    registry["36261:感官-眼科光学相干断层扫描仪:左眼视盘中心Choroid层厚度环均分36等分03区域( μm)"] =_validate_hundred_scale_score
    registry["36262:感官-眼科光学相干断层扫描仪:左眼视盘中心Choroid层厚度环均分36等分04区域( μm)"] =_validate_hundred_scale_score
    registry["36263:感官-眼科光学相干断层扫描仪:左眼视盘中心Choroid层厚度环均分36等分24区域( μm)"] =_validate_hundred_scale_score
    registry["36264:感官-眼科光学相干断层扫描仪:左眼视盘中心Choroid层厚度环均分36等分25区域( μm)"] =_validate_hundred_scale_score
    registry["36265:感官-眼科光学相干断层扫描仪:左眼视盘中心Choroid层厚度环均分36等分26区域( μm)"] =_validate_hundred_scale_score
    registry["36266:感官-眼科光学相干断层扫描仪:左眼视盘中心Choroid层厚度环均分36等分27区域( μm)"] =_validate_hundred_scale_score
    registry["36267:感官-眼科光学相干断层扫描仪:左眼视盘中心Choroid层厚度环均分36等分28区域( μm)"] =_validate_hundred_scale_score
    registry["36268:感官-眼科光学相干断层扫描仪:左眼视盘中心Choroid层厚度环均分36等分29区域( μm)"] =_validate_hundred_scale_score
    registry["36269:感官-眼科光学相干断层扫描仪:左眼视盘中心Choroid层厚度环均分36等分30区域( μm)"] =_validate_hundred_scale_score
    registry["36270:感官-眼科光学相干断层扫描仪:左眼视盘中心Choroid层厚度环均分36等分31区域( μm)"] =_validate_hundred_scale_score
    registry["36271:感官-眼科光学相干断层扫描仪:左眼视盘中心Choroid层厚度环均分36等分32区域( μm)"] =_validate_hundred_scale_score
    registry["36272:感官-眼科光学相干断层扫描仪:左眼视盘中心Choroid层厚度环均分36等分33区域( μm)"] =_validate_hundred_scale_score
    registry["36273:感官-眼科光学相干断层扫描仪:左眼视盘中心Choroid层厚度环均分36等分34区域( μm)"] =_validate_hundred_scale_score
    registry["36274:感官-眼科光学相干断层扫描仪:左眼视盘中心Choroid层厚度环均分36等分36区域( μm)"] =_validate_hundred_scale_score
    registry["36275:感官-眼科光学相干断层扫描仪:左眼视盘中心GCL++层厚度平均( μm)"] =_validate_hundred_scale_score
    registry["36276:感官-眼科光学相干断层扫描仪:左眼视盘中心GCL++层厚度环均分12等分鼻上侧( μm)"] =_validate_hundred_scale_score
    registry["36277:感官-眼科光学相干断层扫描仪:左眼视盘中心GCL++层厚度环均分12等分鼻下侧( μm)"] =_validate_hundred_scale_score
    registry["36278:感官-眼科光学相干断层扫描仪:左眼视盘中心GCL++层厚度环均分36等分22区域( μm)"] =_validate_hundred_scale_score
    registry["36279:感官-眼科光学相干断层扫描仪:左眼视盘中心GCL++层厚度环均分36等分23区域( μm)"] =_validate_hundred_scale_score
    registry["36280:感官-眼科光学相干断层扫描仪:左眼视盘中心GCL++层厚度环均分12等分鼻侧( μm)"] =_validate_hundred_scale_score
    registry["36281:感官-眼科光学相干断层扫描仪:左眼视盘中心GCL++层厚度环均分36等分19区域( μm)"] =_validate_hundred_scale_score
    registry["36282:感官-眼科光学相干断层扫描仪:左眼视盘中心GCL++层厚度环均分36等分08区域( μm)"] =_validate_hundred_scale_score
    registry["36283:感官-眼科光学相干断层扫描仪:左眼视盘中心GCL++层厚度环均分36等分09区域( μm)"] =_validate_hundred_scale_score
    registry["36284:感官-眼科光学相干断层扫描仪:左眼视盘中心RNFL层厚度环均分12等分上侧( μm)"] =_validate_hundred_scale_score
    registry["36285:感官-眼科光学相干断层扫描仪:左眼视盘中心RNFL层厚度环均分36等分10区域( μm)"] =_validate_hundred_scale_score
    registry["36286:感官-眼科光学相干断层扫描仪:左眼视盘中心GCL++层厚度环均分12等分上侧( μm)"] =_validate_hundred_scale_score
    registry["36287:感官-眼科光学相干断层扫描仪:左眼视盘中心GCL++层厚度环均分36等分10区域( μm)"] =_validate_hundred_scale_score
    registry["36288:感官-眼科光学相干断层扫描仪:左眼视盘中心GCL++层厚度环均分36等分15区域( μm)"] =_validate_hundred_scale_score
    registry["36289:感官-眼科光学相干断层扫描仪:左眼视盘中心GCL++层厚度环均分36等分16区域( μm)"] =_validate_hundred_scale_score
    registry["36290:感官-眼科光学相干断层扫描仪:左眼视盘中心GCL++层厚度环均分36等分17区域( μm)"] =_validate_hundred_scale_score
    registry["36291:感官-眼科光学相干断层扫描仪:左眼视盘中心GCL++层厚度环均分36等分18区域( μm)"] =_validate_hundred_scale_score
    registry["36292:感官-眼科光学相干断层扫描仪:左眼视盘中心GCL++层厚度环均分36等分20区域( μm)"] =_validate_hundred_scale_score
    registry["36293:感官-眼科光学相干断层扫描仪:左眼视盘中心GCL++层厚度环均分36等分21区域( μm)"] =_validate_hundred_scale_score
    registry["36294:感官-眼科光学相干断层扫描仪:左眼视盘中心GCL+层厚度环均分12等分颞上侧( μm)"] =_validate_hundred_scale_score
    registry["36295:感官-眼科光学相干断层扫描仪:左眼视盘中心GCL+层厚度环均分36等分04区域( μm)"] =_validate_hundred_scale_score
    registry["36296:感官-眼科光学相干断层扫描仪:左眼视盘中心GCL+层厚度环均分36等分02区域( μm)"] =_validate_hundred_scale_score
    registry["36297:感官-眼科光学相干断层扫描仪:左眼视盘中心GCL+层厚度环均分36等分03区域( μm)"] =_validate_hundred_scale_score
    registry["36298:感官-眼科光学相干断层扫描仪:左眼视盘中心GCL+层厚度环均分36等分05区域( μm)"] =_validate_hundred_scale_score
    registry["36299:感官-眼科光学相干断层扫描仪:左眼视盘中心GCL+层厚度环均分36等分06区域( μm)"] =_validate_hundred_scale_score
    registry["36300:感官-眼科光学相干断层扫描仪:左眼视盘中心GCL+层厚度环均分36等分07区域( μm)"] =_validate_hundred_scale_score
    registry["36301:感官-眼科光学相干断层扫描仪:左眼视盘中心GCL+层厚度环均分36等分31区域( μm)"] =_validate_hundred_scale_score
    registry["36302:感官-眼科光学相干断层扫描仪:左眼视盘中心GCL+层厚度环均分36等分32区域( μm)"] =_validate_hundred_scale_score
    registry["36303:感官-眼科光学相干断层扫描仪:左眼视盘中心GCL+层厚度环均分36等分33区域( μm)"] =_validate_hundred_scale_score
    registry["36304:感官-眼科光学相干断层扫描仪:左眼视盘中心GCL+层厚度环均分36等分35区域( μm)"] =_validate_hundred_scale_score
    registry["36305:感官-眼科光学相干断层扫描仪:左眼视盘中心GCL+层厚度环均分4等分颞侧( μm)"] =_validate_hundred_scale_score
    registry["36306:感官-眼科光学相干断层扫描仪:左眼视盘中心GCL+层厚度环均分6等分颞侧( μm)"] =_validate_hundred_scale_score
    registry["36307:感官-眼科光学相干断层扫描仪:左眼视盘中心GCL+层厚度环均分12等分颞下侧( μm)"] =_validate_hundred_scale_score
    registry["36308:感官-眼科光学相干断层扫描仪:左眼视盘中心GCL+层厚度环均分12等分颞侧( μm)"] =_validate_hundred_scale_score
    registry["36309:感官-眼科光学相干断层扫描仪:左眼视盘中心GCL+层厚度环均分36等分01区域( μm)"] =_validate_hundred_scale_score
    registry["36310:感官-眼科光学相干断层扫描仪:左眼视盘中心GCL+层厚度环均分36等分34区域( μm)"] =_validate_hundred_scale_score
    registry["36311:感官-眼科光学相干断层扫描仪:左眼视盘中心GCL+层厚度环均分36等分36区域( μm)"] =_validate_hundred_scale_score
    registry["36312:感官-眼科光学相干断层扫描仪:左眼视盘中心GCL+层厚度环均分6等分颞下侧( μm)"] =_validate_hundred_scale_score
    registry["36313:感官-眼科光学相干断层扫描仪:左眼视盘中心GCL+层厚度环均分12等分下颞侧( μm)"] =_validate_hundred_scale_score
    registry["36314:感官-眼科光学相干断层扫描仪:左眼视盘中心RNFL层厚度平均( μm)"] =_validate_hundred_scale_score
    registry["36315:感官-眼科光学相干断层扫描仪:左眼视盘中心RNFL层厚度环均分12等分上鼻侧( μm)"] =_validate_hundred_scale_score
    registry["36316:感官-眼科光学相干断层扫描仪:左眼视盘中心RNFL层厚度环均分36等分13区域( μm)"] =_validate_hundred_scale_score
    registry["36317:感官-眼科光学相干断层扫描仪:左眼视盘中心GCL++层厚度环均分12等分上鼻侧( μm)"] =_validate_hundred_scale_score
    registry["36318:感官-眼科光学相干断层扫描仪:左眼视盘中心GCL++层厚度环均分36等分13区域( μm)"] =_validate_hundred_scale_score
    registry["36319:感官-眼科光学相干断层扫描仪:左眼视盘中心RNFL层厚度环均分12等分下侧( μm)"] =_validate_hundred_scale_score
    registry["36320:感官-眼科光学相干断层扫描仪:左眼视盘中心RNFL层厚度环均分36等分28区域( μm)"] =_validate_hundred_scale_score
    registry["36321:感官-眼科光学相干断层扫描仪:左眼视盘中心GCL++层厚度环均分12等分下侧( μm)"] =_validate_hundred_scale_score
    registry["36322:感官-眼科光学相干断层扫描仪:左眼视盘中心GCL++层厚度环均分36等分28区域( μm)"] =_validate_hundred_scale_score
    registry["36323:感官-眼科光学相干断层扫描仪:左眼视盘中心RNFL层厚度环均分12等分下鼻侧( μm)"] =_validate_hundred_scale_score
    registry["36324:感官-眼科光学相干断层扫描仪:左眼视盘中心RNFL层厚度环均分36等分25区域( μm)"] =_validate_hundred_scale_score
    registry["36325:感官-眼科光学相干断层扫描仪:左眼视盘中心GCL++层厚度环均分12等分下鼻侧( μm)"] =_validate_hundred_scale_score
    registry["36326:感官-眼科光学相干断层扫描仪:左眼视盘中心GCL++层厚度环均分36等分25区域( μm)"] =_validate_hundred_scale_score
    registry["36327:感官-眼科光学相干断层扫描仪:左眼视盘中心RNFL层厚度环均分12等分颞上侧( μm)"] =_validate_hundred_scale_score
    registry["36328:感官-眼科光学相干断层扫描仪:左眼视盘中心RNFL层厚度环均分36等分04区域( μm)"] =_validate_hundred_scale_score
    registry["36329:感官-眼科光学相干断层扫描仪:左眼视盘中心RNFL层厚度环均分36等分05区域( μm)"] =_validate_hundred_scale_score
    registry["36330:感官-眼科光学相干断层扫描仪:左眼视盘中心RNFL层厚度环均分12等分颞下侧( μm)"] =_validate_hundred_scale_score
    registry["36331:感官-眼科光学相干断层扫描仪:左眼视盘中心RNFL层厚度环均分36等分34区域( μm)"] =_validate_hundred_scale_score
    registry["36332:感官-眼科光学相干断层扫描仪:左眼视盘中心RNFL层厚度环均分12等分颞侧( μm)"] =_validate_hundred_scale_score
    registry["36333:感官-眼科光学相干断层扫描仪:左眼视盘中心RNFL层厚度环均分36等分01区域( μm)"] =_validate_hundred_scale_score
    registry["36334:感官-眼科光学相干断层扫描仪:左眼视盘中心RNFL层厚度环均分36等分02区域( μm)"] =_validate_hundred_scale_score
    registry["36335:感官-眼科光学相干断层扫描仪:左眼视盘中心RNFL层厚度环均分12等分鼻上侧( μm)"] =_validate_hundred_scale_score
    registry["36336:感官-眼科光学相干断层扫描仪:左眼视盘中心RNFL层厚度环均分12等分鼻下侧( μm)"] =_validate_hundred_scale_score
    registry["36337:感官-眼科光学相干断层扫描仪:左眼视盘中心RNFL层厚度环均分36等分22区域( μm)"] =_validate_hundred_scale_score
    registry["36338:感官-眼科光学相干断层扫描仪:左眼视盘中心RNFL层厚度环均分36等分23区域( μm)"] =_validate_hundred_scale_score
    registry["36339:感官-眼科光学相干断层扫描仪:左眼视盘中心RNFL层厚度环均分12等分鼻侧( μm)"] =_validate_hundred_scale_score
    registry["36340:感官-眼科光学相干断层扫描仪:左眼视盘中心RNFL层厚度环均分36等分19区域( μm)"] =_validate_hundred_scale_score
    registry["36341:感官-眼科光学相干断层扫描仪:左眼视盘中心RNFL层厚度环均分36等分03区域( μm)"] =_validate_hundred_scale_score
    registry["36342:感官-眼科光学相干断层扫描仪:左眼视盘中心RNFL层厚度环均分36等分08区域( μm)"] =_validate_hundred_scale_score
    registry["36343:感官-眼科光学相干断层扫描仪:左眼视盘中心RNFL层厚度环均分36等分09区域( μm)"] =_validate_hundred_scale_score
    registry["36344:感官-眼科光学相干断层扫描仪:左眼视盘中心RNFL层厚度环均分36等分11区域( μm)"] =_validate_hundred_scale_score
    registry["36345:感官-眼科光学相干断层扫描仪:左眼视盘中心GCL++层厚度环均分36等分11区域( μm)"] =_validate_hundred_scale_score
    registry["36346:感官-眼科光学相干断层扫描仪:左眼视盘中心RNFL层厚度环均分36等分12区域( μm)"] =_validate_hundred_scale_score
    registry["36347:感官-眼科光学相干断层扫描仪:左眼视盘中心GCL++层厚度环均分36等分12区域( μm)"] =_validate_hundred_scale_score
    registry["36348:感官-眼科光学相干断层扫描仪:左眼视盘中心RNFL层厚度环均分36等分14区域( μm)"] =_validate_hundred_scale_score
    registry["36349:感官-眼科光学相干断层扫描仪:左眼视盘中心GCL++层厚度环均分36等分14区域( μm)"] =_validate_hundred_scale_score
    registry["36350:感官-眼科光学相干断层扫描仪:左眼视盘中心RNFL层厚度环均分36等分15区域( μm)"] =_validate_hundred_scale_score
    registry["36351:感官-眼科光学相干断层扫描仪:左眼视盘中心RNFL层厚度环均分36等分16区域( μm)"] =_validate_hundred_scale_score
    registry["36352:感官-眼科光学相干断层扫描仪:左眼视盘中心RNFL层厚度环均分36等分17区域( μm)"] =_validate_hundred_scale_score
    registry["36353:感官-眼科光学相干断层扫描仪:左眼视盘中心RNFL层厚度环均分36等分18区域( μm)"] =_validate_hundred_scale_score
    registry["36354:感官-眼科光学相干断层扫描仪:左眼视盘中心RNFL层厚度环均分36等分20区域( μm)"] =_validate_hundred_scale_score
    registry["36355:感官-眼科光学相干断层扫描仪:左眼视盘中心RNFL层厚度环均分36等分21区域( μm)"] =_validate_hundred_scale_score
    registry["36356:感官-眼科光学相干断层扫描仪:左眼视盘中心RNFL层厚度环均分36等分24区域( μm)"] =_validate_hundred_scale_score
    registry["36357:感官-眼科光学相干断层扫描仪:左眼视盘中心GCL++层厚度环均分36等分24区域( μm)"] =_validate_hundred_scale_score
    registry["36358:感官-眼科光学相干断层扫描仪:左眼视盘中心RNFL层厚度环均分36等分29区域( μm)"] =_validate_hundred_scale_score
    registry["36359:感官-眼科光学相干断层扫描仪:左眼视盘中心GCL++层厚度环均分36等分29区域( μm)"] =_validate_hundred_scale_score
    registry["36360:感官-眼科光学相干断层扫描仪:左眼视盘中心RNFL层厚度环均分36等分32区域( μm)"] =_validate_hundred_scale_score
    registry["36361:感官-眼科光学相干断层扫描仪:左眼视盘中心GCL++层厚度环均分36等分32区域( μm)"] =_validate_hundred_scale_score
    registry["36362:感官-眼科光学相干断层扫描仪:左眼视盘中心RNFL层厚度环均分36等分33区域( μm)"] =_validate_hundred_scale_score
    registry["36363:感官-眼科光学相干断层扫描仪:左眼视盘中心GCL++层厚度环均分36等分33区域( μm)"] =_validate_hundred_scale_score
    registry["36364:感官-眼科光学相干断层扫描仪:左眼视盘中心RNFL层厚度环均分36等分35区域( μm)"] =_validate_hundred_scale_score
    registry["36365:感官-眼科光学相干断层扫描仪:左眼视盘中心RNFL层厚度环均分36等分36区域( μm)"] =_validate_hundred_scale_score
    registry["36366:感官-眼科光学相干断层扫描仪:左眼视盘中心RNFL层厚度环均分4等分上侧( μm)"] =_validate_hundred_scale_score
    registry["36367:感官-眼科光学相干断层扫描仪:左眼视盘中心GCL++层厚度环均分4等分上侧( μm)"] =_validate_hundred_scale_score
    registry["36368:感官-眼科光学相干断层扫描仪:左眼视盘中心RNFL层厚度环均分4等分下侧( μm)"] =_validate_hundred_scale_score
    registry["36369:感官-眼科光学相干断层扫描仪:左眼视盘中心GCL++层厚度环均分4等分下侧( μm)"] =_validate_hundred_scale_score
    registry["36370:感官-眼科光学相干断层扫描仪:左眼视盘中心RNFL层厚度环均分4等分颞侧( μm)"] =_validate_hundred_scale_score
    registry["36371:感官-眼科光学相干断层扫描仪:左眼视盘中心RNFL层厚度环均分6等分颞侧( μm)"] =_validate_hundred_scale_score
    registry["36372:感官-眼科光学相干断层扫描仪:左眼视盘中心RNFL层厚度环均分6等分鼻上侧( μm)"] =_validate_hundred_scale_score
    registry["36373:感官-眼科光学相干断层扫描仪:左眼视盘中心GCL++层厚度环均分6等分鼻上侧( μm)"] =_validate_hundred_scale_score
    registry["36374:感官-眼科光学相干断层扫描仪:左眼视盘中心RNFL层厚度环均分6等分鼻下侧( μm)"] =_validate_hundred_scale_score
    registry["36375:感官-眼科光学相干断层扫描仪:左眼视盘中心RNFL层厚度环均分36等分26区域( μm)"] =_validate_hundred_scale_score
    registry["36376:感官-眼科光学相干断层扫描仪:左眼视盘中心RNFL层厚度环均分36等分27区域( μm)"] =_validate_hundred_scale_score
    registry["36377:感官-眼科光学相干断层扫描仪:左眼视盘中心GCL++层厚度环均分6等分鼻下侧( μm)"] =_validate_hundred_scale_score
    registry["36378:感官-眼科光学相干断层扫描仪:左眼视盘中心GCL++层厚度环均分36等分26区域( μm)"] =_validate_hundred_scale_score
    registry["36379:感官-眼科光学相干断层扫描仪:左眼视盘中心GCL++层厚度环均分36等分27区域( μm)"] =_validate_hundred_scale_score
    registry["36380:感官-眼科光学相干断层扫描仪:左眼视盘中心RNFL层厚度环均分4等分鼻侧( μm)"] =_validate_hundred_scale_score
    registry["36381:感官-眼科光学相干断层扫描仪:左眼视盘中心RNFL层厚度环均分6等分鼻侧( μm)"] =_validate_hundred_scale_score
    registry["36382:感官-眼科光学相干断层扫描仪:左眼视盘中心GCL++层厚度环均分4等分鼻侧( μm)"] =_validate_hundred_scale_score
    registry["36383:感官-眼科光学相干断层扫描仪:左眼视盘中心GCL++层厚度环均分6等分鼻侧( μm)"] =_validate_hundred_scale_score
    registry["36384:感官-眼科光学相干断层扫描仪:左眼视盘中心Retina层厚度平均( μm)"] =_validate_hundred_scale_score
    registry["36385:感官-眼科光学相干断层扫描仪:左眼视盘中心Retina层厚度环均分12等分上侧( μm)"] =_validate_hundred_scale_score
    registry["36386:感官-眼科光学相干断层扫描仪:左眼视盘中心Retina层厚度环均分36等分10区域( μm)"] =_validate_hundred_scale_score
    registry["36387:感官-眼科光学相干断层扫描仪:左眼视盘中心Retina层厚度环均分12等分上鼻侧( μm)"] =_validate_hundred_scale_score
    registry["36388:感官-眼科光学相干断层扫描仪:左眼视盘中心Retina层厚度环均分36等分13区域( μm)"] =_validate_hundred_scale_score
    registry["36389:感官-眼科光学相干断层扫描仪:左眼视盘中心Retina层厚度环均分12等分鼻上侧( μm)"] =_validate_hundred_scale_score
    registry["36390:感官-眼科光学相干断层扫描仪:左眼视盘中心Retina层厚度环均分36等分16区域( μm)"] =_validate_hundred_scale_score
    registry["36391:感官-眼科光学相干断层扫描仪:左眼视盘中心Retina层厚度环均分12等分鼻下侧( μm)"] =_validate_hundred_scale_score
    registry["36392:感官-眼科光学相干断层扫描仪:左眼视盘中心Retina层厚度环均分36等分22区域( μm)"] =_validate_hundred_scale_score
    registry["36393:感官-眼科光学相干断层扫描仪:左眼视盘中心Retina层厚度环均分36等分23区域( μm)"] =_validate_hundred_scale_score
    registry["36394:感官-眼科光学相干断层扫描仪:左眼视盘中心Retina层厚度环均分12等分鼻侧( μm)"] =_validate_hundred_scale_score
    registry["36395:感官-眼科光学相干断层扫描仪:左眼视盘中心Retina层厚度环均分36等分18区域( μm)"] =_validate_hundred_scale_score
    registry["36396:感官-眼科光学相干断层扫描仪:左眼视盘中心Retina层厚度环均分36等分19区域( μm)"] =_validate_hundred_scale_score
    registry["36397:感官-眼科光学相干断层扫描仪:左眼视盘中心Retina层厚度环均分36等分20区域( μm)"] =_validate_hundred_scale_score
    registry["36398:感官-眼科光学相干断层扫描仪:左眼视盘中心Retina层厚度环均分36等分08区域( μm)"] =_validate_hundred_scale_score
    registry["36399:感官-眼科光学相干断层扫描仪:左眼视盘中心Retina层厚度环均分36等分09区域( μm)"] =_validate_hundred_scale_score
    registry["36400:感官-眼科光学相干断层扫描仪:左眼视盘中心Retina层厚度环均分36等分14区域( μm)"] =_validate_hundred_scale_score
    registry["36401:感官-眼科光学相干断层扫描仪:左眼视盘中心Retina层厚度环均分36等分15区域( μm)"] =_validate_hundred_scale_score
    registry["36402:感官-眼科光学相干断层扫描仪:左眼视盘中心Retina层厚度环均分36等分17区域( μm)"] =_validate_hundred_scale_score
    registry["36403:感官-眼科光学相干断层扫描仪:左眼视盘中心Retina层厚度环均分36等分21区域( μm)"] =_validate_hundred_scale_score
    registry["36404:感官-眼科光学相干断层扫描仪:左眼视盘中心Retina层厚度环均分36等分24区域( μm)"] =_validate_hundred_scale_score
    registry["36405:感官-眼科光学相干断层扫描仪:左眼视盘中心Retina层厚度环均分4等分上侧( μm)"] =_validate_hundred_scale_score
    registry["36406:感官-眼科光学相干断层扫描仪:左眼视盘中心Retina层厚度环均分4等分下侧( μm)"] =_validate_hundred_scale_score
    registry["36407:感官-眼科光学相干断层扫描仪:左眼视盘中心Retina层厚度环均分4等分鼻侧( μm)"] =_validate_hundred_scale_score
    registry["36408:感官-眼科光学相干断层扫描仪:左眼视盘中心Retina层厚度环均分6等分鼻侧( μm)"] =_validate_hundred_scale_score
    registry["36409:感官-眼科光学相干断层扫描仪:左眼视盘中心Retina层厚度环均分6等分鼻上侧( μm)"] =_validate_hundred_scale_score
    registry["36410:感官-眼科光学相干断层扫描仪:左眼视盘中心Retina层厚度环均分36等分11区域( μm)"] =_validate_hundred_scale_score
    registry["36411:感官-眼科光学相干断层扫描仪:左眼视盘中心Retina层厚度环均分36等分12区域( μm)"] =_validate_hundred_scale_score
    registry["36412:感官-眼科光学相干断层扫描仪:左眼视盘中心Retina层厚度环均分6等分鼻下侧( μm)"] =_validate_hundred_scale_score
    registry["36413:感官-眼科光学相干断层扫描仪:左眼视盘中心Retina层厚度环均分12等分下鼻侧( μm)"] =_validate_hundred_scale_score
    registry["36414:感官-眼科光学相干断层扫描仪:左眼视盘中心Retina层厚度环均分12等分下侧( μm)"] =_validate_hundred_scale_score
    registry["36415:感官-眼科光学相干断层扫描仪:左眼视盘中心Retina层厚度环均分36等分25区域( μm)"] =_validate_hundred_scale_score
    registry["36416:感官-眼科光学相干断层扫描仪:左眼视盘中心Retina层厚度环均分36等分26区域( μm)"] =_validate_hundred_scale_score
    registry["36417:感官-眼科光学相干断层扫描仪:左眼视盘中心Retina层厚度环均分36等分27区域( μm)"] =_validate_hundred_scale_score
    registry["36418:感官-眼科光学相干断层扫描仪:左眼视盘中心Retina层厚度环均分36等分28区域( μm)"] =_validate_hundred_scale_score
    registry["36419:感官-眼科光学相干断层扫描仪:左眼视盘中心Retina层厚度环均分36等分29区域( μm)"] =_validate_hundred_scale_score
    registry["36420:感官-眼科光学相干断层扫描仪:左眼视盘垂直直径(mm)"] =_validate_hundred_scale_score
    registry["36421:感官-眼科光学相干断层扫描仪:左眼视盘水平直径(mm)"] =_validate_hundred_scale_score
    registry["36422:感官-眼科光学相干断层扫描仪:左眼视盘面积(mm2)"] =_validate_hundred_scale_score
    registry["36423:感官-眼科光学相干断层扫描仪:左眼颞侧视盘中心外层密度(%)"] =_validate_hundred_scale_score
    registry["36424:感官-眼科光学相干断层扫描仪:左眼颞侧视盘中心浅层密度(%)"] =_validate_hundred_scale_score
    registry["36425:感官-眼科光学相干断层扫描仪:左眼颞侧视盘中心深层密度(%)"] =_validate_hundred_scale_score
    registry["36426:感官-眼科光学相干断层扫描仪:左眼颞侧视盘中心脉络膜层密度(%)"] =_validate_hundred_scale_score
    registry["36427:感官-眼科光学相干断层扫描仪:左眼黄斑中心Choroid层厚度内环上侧( μm)"] =_validate_hundred_scale_score
    registry["36428:感官-眼科光学相干断层扫描仪:左眼黄斑中心Choroid层厚度内环鼻侧( μm)"] =_validate_hundred_scale_score
    registry["36429:感官-眼科光学相干断层扫描仪:左眼黄斑中心Choroid层厚度外环鼻侧( μm)"] =_validate_hundred_scale_score
    registry["36430:感官-眼科光学相干断层扫描仪:左眼黄斑中心Choroid层厚度外环上侧( μm)"] =_validate_hundred_scale_score
    registry["36431:感官-眼科光学相干断层扫描仪:左眼黄斑中心Choroid层厚度外环颞侧( μm)"] =_validate_hundred_scale_score
    registry["36432:感官-眼科光学相干断层扫描仪:左眼黄斑中心Choroid层厚度中心( μm)"] =_validate_hundred_scale_score
    registry["36433:感官-眼科光学相干断层扫描仪:左眼黄斑中心Choroid层厚度内环下侧( μm)"] =_validate_hundred_scale_score
    registry["36434:感官-眼科光学相干断层扫描仪:左眼黄斑中心Choroid层厚度内环颞侧( μm)"] =_validate_hundred_scale_score
    registry["36435:感官-眼科光学相干断层扫描仪:左眼黄斑中心Choroid层厚度外环下侧( μm)"] =_validate_hundred_scale_score
    registry["36436:感官-眼科光学相干断层扫描仪:左眼黄斑中心Choroid层厚度平均( μm)"] =_validate_hundred_scale_score
    registry["36437:感官-眼科光学相干断层扫描仪:左眼鼻侧视盘中心外层密度(%)"] = _validate_hundred_scale_score
    registry["36438:感官-眼科光学相干断层扫描仪:左眼鼻侧视盘中心浅层密度(%)"] = _validate_hundred_scale_score
    registry["36439:感官-眼科光学相干断层扫描仪:左眼鼻侧视盘中心深层密度(%)"] = _validate_hundred_scale_score
    registry["36955:感官-眼科光学相干断层扫描仪:FAZ区域夹角(右)"] =_validate_hundred_scale_score
    registry["36956:感官-眼科光学相干断层扫描仪:FAZ区域夹角(左)"] =_validate_hundred_scale_score

def is_between_0_and_1(feature_key, final_value, payload) -> bool:
    """
    判断数值是否在 0-1（含）之间，接受字符串数字或数值类型。
    """
    try:
        num = float(final_value)
    except (TypeError, ValueError):
        return False
    return 0 <= num <= 1

def _validate_hundred_scale_score(feature_key, final_value, payload) -> bool:
    """
    - 范围为0-100之间的浮点数或整数。
    """
    try:
        score = float(final_value)
    except (TypeError, ValueError):
        return False
    return 0 <= score <= 100
